import { z } from "zod";
import type { LocalSyncReadiness, RemoteBranchCleanupReadiness, PostMergeHandoff, PostMergeStateSnapshot, LocalSyncResult, RemoteBranchCleanupResult } from "../types/index.js";

export const localSyncReadinessSchema: z.ZodType<LocalSyncReadiness> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  postMergeHandoffId: z.string(),
  remoteLandingResultId: z.string(),
  landingPackageId: z.string(),
  projectId: z.string().nullable(),
  status: z.enum(["ready", "already-current", "not-merged", "provider-unavailable", "dirty-source", "wrong-branch", "missing-base", "fetch-failed", "not-fast-forward"]),
  canSync: z.boolean(),
  summary: z.string(),
  reason: z.string(),
  confirmEffect: z.string(),
  riskSummary: z.string(),
  readinessArtifact: z.string(),
  evidenceRefs: z.array(z.string()),
  createdAt: z.string(),
});

export const cleanupReadinessSchema: z.ZodType<RemoteBranchCleanupReadiness> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  postMergeHandoffId: z.string(),
  remoteLandingResultId: z.string(),
  landingPackageId: z.string(),
  projectId: z.string().nullable(),
  status: z.enum(["ready", "not-merged", "provider-unavailable", "missing-head", "already-deleted", "unsafe-head", "delete-unavailable"]),
  canCleanup: z.boolean(),
  headBranch: z.string().nullable().optional(),
  remoteName: z.string().optional(),
  summary: z.string(),
  reason: z.string(),
  confirmEffect: z.string(),
  riskSummary: z.string(),
  readinessArtifact: z.string(),
  evidenceRefs: z.array(z.string()),
  createdAt: z.string(),
});

export const handoffSchema: z.ZodType<PostMergeHandoff> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  remoteLandingResultId: z.string(),
  landingPackageId: z.string(),
  prDraftPackageId: z.string(),
  projectId: z.string().nullable(),
  prUrl: z.string().optional(),
  status: z.enum(["merged", "not-merged"]),
  summary: z.string(),
  localStatusSummary: z.string(),
  cleanupSummary: z.string(),
  stateSnapshotArtifact: z.string(),
  summaryArtifact: z.string(),
  evidenceRefs: z.array(z.string()),
  localSyncReadiness: localSyncReadinessSchema,
  remoteBranchCleanupReadiness: cleanupReadinessSchema,
  createdAt: z.string(),
});

export const stateSnapshotSchema: z.ZodType<PostMergeStateSnapshot> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  remoteLandingResultId: z.string(),
  landingPackageId: z.string(),
  prDraftPackageId: z.string(),
  projectId: z.string().nullable(),
  prUrl: z.string().optional(),
  prState: z.string(),
  baseBranch: z.string().nullable().optional(),
  headBranch: z.string().nullable().optional(),
  mergeCommit: z.string().nullable().optional(),
  mergedAt: z.string().nullable().optional(),
  currentBranch: z.string().nullable().optional(),
  workingTreeClean: z.boolean().nullable(),
  localHead: z.string().nullable().optional(),
  remoteName: z.string().optional(),
  remoteBaseHead: z.string().nullable().optional(),
  remoteHeadBranchExists: z.boolean().nullable().optional(),
  canFastForward: z.boolean(),
  alreadyCurrent: z.boolean(),
  evidenceRefs: z.array(z.string()),
  createdAt: z.string(),
});

export const localSyncResultSchema: z.ZodType<LocalSyncResult> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  readinessId: z.string(),
  postMergeHandoffId: z.string(),
  remoteLandingResultId: z.string(),
  landingPackageId: z.string(),
  projectId: z.string().nullable(),
  status: z.enum(["synced", "skipped", "failed"]),
  beforeHead: z.string().nullable().optional(),
  afterHead: z.string().nullable().optional(),
  failureReason: z.string().optional(),
  artifactRefs: z.array(z.string()),
  createdAt: z.string(),
});

export const cleanupResultSchema: z.ZodType<RemoteBranchCleanupResult> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  readinessId: z.string(),
  postMergeHandoffId: z.string(),
  remoteLandingResultId: z.string(),
  landingPackageId: z.string(),
  projectId: z.string().nullable(),
  status: z.enum(["deleted", "skipped", "failed"]),
  headBranch: z.string().nullable().optional(),
  remoteName: z.string().optional(),
  failureReason: z.string().optional(),
  artifactRefs: z.array(z.string()),
  createdAt: z.string(),
});
