import { z } from "zod";
import type { PrFeedbackSnapshot, PrFeedbackSummary, PrFeedbackReworkAttempt, ReviewFeedbackUserContext } from "../types/index.js";

export const snapshotSchema: z.ZodType<PrFeedbackSnapshot> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  prDraftPackageId: z.string(),
  landingPackageId: z.string(),
  projectId: z.string().nullable(),
  prUrl: z.string().optional(),
  state: z.string(),
  isDraft: z.boolean(),
  reviewDecision: z.string().nullable().optional(),
  headRefName: z.string().nullable().optional(),
  baseRefName: z.string().nullable().optional(),
  headRefOid: z.string().nullable().optional(),
  baseRefOid: z.string().nullable().optional(),
  reviews: z.array(z.unknown()),
  comments: z.array(z.unknown()),
  inlineComments: z.array(z.object({
    id: z.string(),
    body: z.string(),
    path: z.string().nullable().optional(),
    line: z.number().nullable().optional(),
    side: z.string().nullable().optional(),
    author: z.string().nullable().optional(),
    createdAt: z.string().nullable().optional(),
    url: z.string().nullable().optional(),
    inReplyToId: z.string().nullable().optional(),
  })).optional(),
  threadCapability: z.object({
    provider: z.literal("github-cli"),
    canReadThreads: z.boolean(),
    canResolveThreads: z.boolean(),
    reason: z.string().optional(),
    evidenceRefs: z.array(z.string()),
  }).optional(),
  threadFindings: z.array(z.object({
    id: z.string(),
    threadId: z.string().optional(),
    commentId: z.string().optional(),
    path: z.string().nullable().optional(),
    line: z.number().nullable().optional(),
    body: z.string(),
    author: z.string().nullable().optional(),
    resolved: z.boolean().optional(),
    actionable: z.boolean(),
  })).optional(),
  statusCheckRollup: z.array(z.unknown()),
  rawArtifact: z.string(),
  snapshotArtifact: z.string(),
  summaryArtifact: z.string(),
  createdAt: z.string(),
});

export const summarySchema: z.ZodType<PrFeedbackSummary> = z.object({
  version: z.literal("1.0"),
  snapshotId: z.string(),
  prDraftPackageId: z.string(),
  landingPackageId: z.string(),
  classification: z.enum(["no-action", "checks-failed", "changes-requested", "inline-comments-actionable", "comments-only", "user-pushback-requested", "provider-unavailable", "stale-pr"]),
  actionable: z.boolean(),
  summary: z.string(),
  reviewDecision: z.string().nullable().optional(),
  commentsCount: z.number(),
  inlineCommentsCount: z.number().optional(),
  actionableCommentsCount: z.number().optional(),
  failedChecksCount: z.number(),
  evidenceRefs: z.array(z.string()),
  recommendedAction: z.string(),
  createdAt: z.string(),
});

export const reworkSchema: z.ZodType<PrFeedbackReworkAttempt> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  prDraftPackageId: z.string(),
  landingPackageId: z.string(),
  snapshotId: z.string(),
  userContextId: z.string().optional(),
  reworkContextArtifact: z.string().optional(),
  status: z.enum(["started", "completed", "failed"]),
  agentTaskId: z.string().optional(),
  artifactRefs: z.array(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const userContextSchema: z.ZodType<ReviewFeedbackUserContext> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  landingPackageId: z.string(),
  prDraftPackageId: z.string().optional(),
  intent: z.enum(["rework", "reply", "pushback", "clarify"]),
  message: z.string(),
  createdAt: z.string(),
  artifactRef: z.string(),
});
