import type { SchedulerReconcileSnapshot, SchedulerRuntimeClaimReservation, SchedulerRuntimeState, SchedulerRuntimeWorkerAudit, SchedulerRuntimeWorkerResult, SchedulerRuntimeWorkerReworkPlan, SchedulerRuntimeWorkerReworkStart, SchedulerRuntimeWorkerStart, SchedulerRuntimeWorkerValidation } from "./types.js";

export function renderSchedulerRuntimeStateMarkdown(state: SchedulerRuntimeState): string {
  const lines = [
    `# SchedulerRuntimeState ${state.id}`,
    "",
    `Status: ${state.status}`,
    `Change: ${state.changeId}`,
    `SchedulerRun: ${state.schedulerRunId}`,
    `SchedulerContract: ${state.schedulerContractId}`,
    "",
    "## Summary",
    "",
    `- Waves: ${state.waves.length}`,
    `- Claim intents: ${state.claimIntents.length}`,
    `- Planned slot demand: ${state.plannedSlotDemand}`,
    `- Max planned wave width: ${state.maxPlannedWaveWidth}`,
    `- Blocked entries: ${state.blockedCount}`,
    `- Last reconcile snapshot: ${state.lastReconcileSnapshotId ?? "none"}`,
    `- Last claim reservation: ${state.lastClaimReservationId ?? "none"}`,
    "",
    "## Waves",
    "",
    ...state.waves.map((wave) => [
      `### Wave ${wave.waveIndex + 1}`,
      "",
      `- Status: ${wave.status}`,
      `- Claim intents: ${wave.claimIntentIds.join(", ") || "none"}`,
      `- Candidate claims: ${wave.candidateCount}`,
      `- Blocked claims: ${wave.blockedCount}`,
      `- Planned slot demand: ${wave.plannedSlotDemand}`,
      `- Blocked reasons: ${wave.blockedReasons.length ? wave.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This runtime shell is not a parallel executor. It does not allocate WorkerLeases, create WorkerSessions, create TaskRuns, start agents, create worktrees, create runs, or authorize execution.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeClaimReservationMarkdown(reservation: SchedulerRuntimeClaimReservation): string {
  const lines = [
    `# SchedulerRuntimeClaimReservation ${reservation.id}`,
    "",
    `Status: ${reservation.status}`,
    `Change: ${reservation.changeId}`,
    `SchedulerRun: ${reservation.schedulerRunId}`,
    `RuntimeState: ${reservation.schedulerRuntimeStateId}`,
    `ReconcileSnapshot: ${reservation.schedulerReconcileSnapshotId}`,
    "",
    "## Summary",
    "",
    `- Reserved claims: ${reservation.reservedCount}`,
    `- Blocked claims: ${reservation.blockedCount}`,
    `- Source locks: ${reservation.sourceLockCount}`,
    `- Supersedes reservation: ${reservation.supersedesReservationId ?? "none"}`,
    "",
    "## Waves",
    "",
    ...reservation.waves.map((wave) => [
      `### Wave ${wave.waveIndex + 1}`,
      "",
      `- Status: ${wave.status}`,
      `- Reservation intents: ${wave.reservationIntentIds.join(", ") || "none"}`,
      `- Reserved claims: ${wave.reservedCount}`,
      `- Blocked claims: ${wave.blockedCount}`,
      `- Planned slot demand: ${wave.plannedSlotDemand}`,
      `- Blocked reasons: ${wave.blockedReasons.length ? wave.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Reservation Intents",
    "",
    ...reservation.reservationIntents.map((intent) => [
      `### ${intent.reservationIntentId}`,
      "",
      `- Claim intent: ${intent.claimIntentId}`,
      `- Status: ${intent.status}`,
      `- Planned worker key: ${intent.plannedWorkerKey}`,
      `- Node: ${intent.nodeId}`,
      `- Unit: ${intent.unitId}`,
      `- Wave: ${intent.waveIndex + 1}`,
      `- Planned slot demand: ${intent.plannedSlotDemand}`,
      `- Source scopes: ${intent.sourceScopes.join(", ") || "none"}`,
      `- Blocked reasons: ${intent.blockedReasons.length ? intent.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Source Locks",
    "",
    ...(reservation.sourceLocks.length ? reservation.sourceLocks.map((lock) => [
      `### ${lock.scope}`,
      "",
      `- Status: ${lock.status}`,
      `- Wave: ${lock.waveIndex + 1}`,
      `- Reservation intents: ${lock.reservationIntentIds.join(", ") || "none"}`,
      `- Blocked reasons: ${lock.blockedReasons.length ? lock.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")) : ["- none", ""]),
    "## Boundary",
    "",
    "This claim reservation is runtime coordination evidence only. It is not a WorkerLease, WorkerSession, TaskRun, worktree, run, slot allocation, worker start, or execution authorization.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerReconcileSnapshotMarkdown(snapshot: SchedulerReconcileSnapshot): string {
  const lines = [
    `# SchedulerReconcileSnapshot ${snapshot.id}`,
    "",
    `Status: ${snapshot.status}`,
    `Change: ${snapshot.changeId}`,
    `SchedulerRun: ${snapshot.schedulerRunId}`,
    `RuntimeState: ${snapshot.schedulerRuntimeStateId}`,
    "",
    "## Summary",
    "",
    `- Waves: ${snapshot.waves.length}`,
    `- Claim intents: ${snapshot.claimIntents.length}`,
    `- Planned slot demand: ${snapshot.plannedSlotDemand}`,
    `- Max planned wave width: ${snapshot.maxPlannedWaveWidth}`,
    `- Blocked entries: ${snapshot.blockedCount}`,
    `- Warnings: ${snapshot.warningCount}`,
    `- Recovery checkpoint: ${snapshot.recoveryCheckpoint}`,
    "",
    "## Warnings",
    "",
    ...(snapshot.warnings.length ? snapshot.warnings.map((warning) => `- ${warning}`) : ["- none"]),
    "",
    "## Claim Intents",
    "",
    ...snapshot.claimIntents.map((claim) => [
      `### ${claim.claimIntentId}`,
      "",
      `- Status: ${claim.status}`,
      `- Planned worker key: ${claim.plannedWorkerKey}`,
      `- Node: ${claim.nodeId}`,
      `- Unit: ${claim.unitId}`,
      `- Wave: ${claim.waveIndex + 1}`,
      `- Planned slot demand: ${claim.plannedSlotDemand}`,
      `- Source scopes: ${claim.sourceScopes.join(", ") || "none"}`,
      `- Blocked reasons: ${claim.blockedReasons.length ? claim.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This reconcile snapshot is runtime shell evidence only. It does not claim workers, allocate slots, create runtime-continuity sidecars, start agents, create worktrees, create runs, or authorize execution.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerStartMarkdown(workerStart: SchedulerRuntimeWorkerStart): string {
  const lines = [
    `# SchedulerRuntimeWorkerStart ${workerStart.id}`,
    "",
    `Status: ${workerStart.status}`,
    `Change: ${workerStart.changeId}`,
    `SchedulerRun: ${workerStart.schedulerRunId}`,
    `ClaimReservation: ${workerStart.schedulerClaimReservationId}`,
    "",
    "## Worker",
    "",
    `- Reservation intent: ${workerStart.reservationIntentId}`,
    `- Claim intent: ${workerStart.claimIntentId}`,
    `- Planned worker key: ${workerStart.plannedWorkerKey}`,
    `- Node: ${workerStart.nodeId}`,
    `- Unit: ${workerStart.unitId}`,
    `- Wave: ${workerStart.waveIndex + 1}`,
    `- Stage: ${workerStart.stage}`,
    `- Task: ${workerStart.taskId}`,
    `- TaskRun: ${workerStart.taskRunId}`,
    `- WorkerLease: ${workerStart.workerLeaseId}`,
    `- TaskRun role: ${workerStart.taskRunRoleId}`,
    `- Agent role: ${workerStart.agentRoleId}`,
    `- Worktree: ${workerStart.worktreeId ?? "none"}`,
    `- Code run: ${workerStart.runId ?? "none"}`,
    ...(workerStart.failureReason ? [`- Failure: ${workerStart.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This worker-start evidence records one scheduler claim's coder-stage start only. It does not start a full wave, validation, audit, bounded rework, scheduler loop, slot allocator, child Change, WorkflowRun, TaskQueueRun, or AgentTask.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerResultMarkdown(result: SchedulerRuntimeWorkerResult): string {
  const lines = [
    `# SchedulerRuntimeWorkerResult ${result.id}`,
    "",
    `Status: ${result.status}`,
    `Change: ${result.changeId}`,
    `SchedulerRun: ${result.schedulerRunId}`,
    `WorkerStart: ${result.schedulerWorkerStartId}`,
    `ClaimReservation: ${result.schedulerClaimReservationId}`,
    "",
    "## Worker Result",
    "",
    `- Reservation intent: ${result.reservationIntentId}`,
    `- Claim intent: ${result.claimIntentId}`,
    `- Planned worker key: ${result.plannedWorkerKey}`,
    `- Node: ${result.nodeId}`,
    `- Unit: ${result.unitId}`,
    `- Wave: ${result.waveIndex + 1}`,
    `- Stage: ${result.stage}`,
    `- Task: ${result.taskId}`,
    `- TaskRun: ${result.taskRunId}`,
    `- TaskRun status: ${result.taskRunStatus}`,
    `- WorkerLease: ${result.workerLeaseId}`,
    `- WorkerLease status: ${result.workerLeaseStatus}`,
    `- Agent role: ${result.agentRoleId}`,
    `- Worktree: ${result.worktreeId ?? "none"}`,
    `- Code run: ${result.runId ?? "none"}`,
    `- Code run status: ${result.runStatus ?? "none"}`,
    ...(result.failureReason ? [`- Failure: ${result.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This worker-result evidence reconciles one scheduler coder-stage worker only. Coder success means evidence-ready for later validation/audit; it is not task completion, source apply, whole-wave dispatch, scheduler loop, or parallel executor authorization.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerValidationMarkdown(validation: SchedulerRuntimeWorkerValidation): string {
  const lines = [
    `# SchedulerRuntimeWorkerValidation ${validation.id}`,
    "",
    `Status: ${validation.status}`,
    `Change: ${validation.changeId}`,
    `SchedulerRun: ${validation.schedulerRunId}`,
    `WorkerResult: ${validation.schedulerWorkerResultId}`,
    `WorkerStart: ${validation.schedulerWorkerStartId}`,
    `ClaimReservation: ${validation.schedulerClaimReservationId}`,
    "",
    "## Worker Validation",
    "",
    `- Reservation intent: ${validation.reservationIntentId}`,
    `- Claim intent: ${validation.claimIntentId}`,
    `- Planned worker key: ${validation.plannedWorkerKey}`,
    `- Node: ${validation.nodeId}`,
    `- Unit: ${validation.unitId}`,
    `- Wave: ${validation.waveIndex + 1}`,
    `- Stage: ${validation.stage}`,
    `- Task: ${validation.taskId}`,
    `- TaskRun: ${validation.taskRunId}`,
    `- TaskRun status: ${validation.taskRunStatus}`,
    `- WorkerLease: ${validation.workerLeaseId}`,
    `- Worktree: ${validation.worktreeId}`,
    `- Code run: ${validation.codeRunId}`,
    `- Validation run: ${validation.validationRunId}`,
    `- Validation status: ${validation.validationStatus}`,
    ...(validation.failureReason ? [`- Failure: ${validation.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This worker-validation evidence validates one scheduler coder-stage worker worktree only. Passed validation is not task completion; audit remains a later gate. It does not start audit, bounded rework, a next worker, whole-wave dispatch, scheduler loop, apply, or merge.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerAuditMarkdown(audit: SchedulerRuntimeWorkerAudit): string {
  const lines = [
    `# SchedulerRuntimeWorkerAudit ${audit.id}`,
    "",
    `Status: ${audit.status}`,
    `Change: ${audit.changeId}`,
    `SchedulerRun: ${audit.schedulerRunId}`,
    `WorkerValidation: ${audit.schedulerWorkerValidationId}`,
    `WorkerResult: ${audit.schedulerWorkerResultId}`,
    `WorkerStart: ${audit.schedulerWorkerStartId}`,
    `ClaimReservation: ${audit.schedulerClaimReservationId}`,
    "",
    "## Worker Audit",
    "",
    `- Reservation intent: ${audit.reservationIntentId}`,
    `- Claim intent: ${audit.claimIntentId}`,
    `- Planned worker key: ${audit.plannedWorkerKey}`,
    `- Node: ${audit.nodeId}`,
    `- Unit: ${audit.unitId}`,
    `- Wave: ${audit.waveIndex + 1}`,
    `- Stage: ${audit.stage}`,
    `- Task: ${audit.taskId}`,
    `- TaskRun: ${audit.taskRunId}`,
    `- TaskRun status: ${audit.taskRunStatus}`,
    `- WorkerLease: ${audit.workerLeaseId}`,
    `- Worktree: ${audit.worktreeId}`,
    `- Code run: ${audit.codeRunId}`,
    `- Validation run: ${audit.validationRunId}`,
    `- Validation status: ${audit.validationStatus}`,
    `- Audit run: ${audit.auditRunId}`,
    `- Audit status: ${audit.auditStatus}`,
    ...(audit.failureReason ? [`- Failure: ${audit.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This worker-audit evidence audits one scheduler coder-stage worker worktree only. Approved audit may complete that TaskRun; blocked or failed audit only blocks the current worker path. It does not start rework, a next worker, whole-wave dispatch, scheduler loop, apply, or merge.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerReworkPlanMarkdown(plan: SchedulerRuntimeWorkerReworkPlan): string {
  const lines = [
    `# SchedulerRuntimeWorkerReworkPlan ${plan.id}`,
    "",
    `Status: ${plan.status}`,
    `Change: ${plan.changeId}`,
    `SchedulerRun: ${plan.schedulerRunId}`,
    `Blocking source: ${plan.blockingSource}`,
    `WorkerValidation: ${plan.schedulerWorkerValidationId}`,
    `WorkerAudit: ${plan.schedulerWorkerAuditId ?? "none"}`,
    `ClaimReservation: ${plan.schedulerClaimReservationId}`,
    "",
    "## Rework Intent",
    "",
    `- Reason: ${plan.reworkReason}`,
    `- Reservation intent: ${plan.reservationIntentId}`,
    `- Claim intent: ${plan.claimIntentId}`,
    `- Planned worker key: ${plan.plannedWorkerKey}`,
    `- Node: ${plan.nodeId}`,
    `- Unit: ${plan.unitId}`,
    `- Wave: ${plan.waveIndex + 1}`,
    `- Stage: ${plan.stage}`,
    `- Task: ${plan.taskId}`,
    `- Current TaskRun: ${plan.taskRunId}`,
    `- Current TaskRun status: ${plan.taskRunStatus}`,
    `- WorkerLease: ${plan.workerLeaseId}`,
    `- Target worktree: ${plan.targetWorktreeId}`,
    `- Target code run: ${plan.targetCodeRunId}`,
    `- Validation run: ${plan.validationRunId}`,
    `- Validation status: ${plan.validationStatus}`,
    `- Audit run: ${plan.auditRunId ?? "none"}`,
    `- Audit status: ${plan.auditStatus ?? "none"}`,
    `- Future code gate: ${plan.futureCodeGateMode}`,
    "",
    "## Recovery Key Inputs",
    "",
    ...(plan.recoveryKeyInputs.length ? plan.recoveryKeyInputs.map((item) => `- ${item}`) : ["- none"]),
    "",
    "## Boundary",
    "",
    "This rework plan is non-executing scheduler evidence. It does not start rework, call startCodeRun(), create TaskRuns, WorkerLeases, WorkerSessions, RuntimeWorkspaces, EventSources, worktrees, runs, AgentTasks, WorkflowRuns, TaskQueueRuns, child Changes, next workers, whole-wave dispatch, apply, or merge.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerReworkStartMarkdown(start: SchedulerRuntimeWorkerReworkStart): string {
  const lines = [
    `# SchedulerRuntimeWorkerReworkStart ${start.id}`,
    "",
    `Status: ${start.status}`,
    `Change: ${start.changeId}`,
    `SchedulerRun: ${start.schedulerRunId}`,
    `ReworkPlan: ${start.schedulerWorkerReworkPlanId}`,
    `ClaimReservation: ${start.schedulerClaimReservationId}`,
    "",
    "## Rework Start",
    "",
    `- Reservation intent: ${start.reservationIntentId}`,
    `- Claim intent: ${start.claimIntentId}`,
    `- Planned worker key: ${start.plannedWorkerKey}`,
    `- Node: ${start.nodeId}`,
    `- Unit: ${start.unitId}`,
    `- Wave: ${start.waveIndex + 1}`,
    `- Stage: ${start.stage}`,
    `- Task: ${start.taskId}`,
    `- Original TaskRun: ${start.originalTaskRunId}`,
    `- Original WorkerLease: ${start.originalWorkerLeaseId}`,
    `- Rework TaskRun: ${start.reworkTaskRunId}`,
    `- Rework WorkerLease: ${start.reworkWorkerLeaseId}`,
    `- TaskRun role: ${start.taskRunRoleId}`,
    `- Agent role: ${start.agentRoleId}`,
    `- Worktree: ${start.worktreeId}`,
    `- Original code run: ${start.originalCodeRunId}`,
    `- Rework code run: ${start.reworkRunId ?? "none"}`,
    ...(start.failureReason ? [`- Failure: ${start.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This rework-start evidence records one same-worktree scheduler rework-coder start only. It does not create a new worktree, validate or audit the rework result, reconcile the rework result, start another worker, run a whole wave, run IntegrationCheck, apply, merge, create child Changes, or become a full parallel executor.",
    "",
  ];
  return lines.join("\n");
}
