import type { SchedulerReconcileSnapshot, SchedulerRuntimeState } from "./types.js";

export function renderSchedulerRuntimeStateMarkdown(state: SchedulerRuntimeState): string {
  const lines = [
    `# SchedulerRuntimeState ${state.id}`,
    "",
    `Status: ${state.status}`,
    `Change: ${state.changeId}`,
    `SchedulerRun: ${state.schedulerRunId}`,
    `SchedulerContract: ${state.schedulerContractId}`,
    "",
    "## Summary",
    "",
    `- Waves: ${state.waves.length}`,
    `- Claim intents: ${state.claimIntents.length}`,
    `- Planned slot demand: ${state.plannedSlotDemand}`,
    `- Max planned wave width: ${state.maxPlannedWaveWidth}`,
    `- Blocked entries: ${state.blockedCount}`,
    `- Last reconcile snapshot: ${state.lastReconcileSnapshotId ?? "none"}`,
    "",
    "## Waves",
    "",
    ...state.waves.map((wave) => [
      `### Wave ${wave.waveIndex + 1}`,
      "",
      `- Status: ${wave.status}`,
      `- Claim intents: ${wave.claimIntentIds.join(", ") || "none"}`,
      `- Candidate claims: ${wave.candidateCount}`,
      `- Blocked claims: ${wave.blockedCount}`,
      `- Planned slot demand: ${wave.plannedSlotDemand}`,
      `- Blocked reasons: ${wave.blockedReasons.length ? wave.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This runtime shell is not a parallel executor. It does not allocate WorkerLeases, create WorkerSessions, create TaskRuns, start agents, create worktrees, create runs, or authorize execution.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerReconcileSnapshotMarkdown(snapshot: SchedulerReconcileSnapshot): string {
  const lines = [
    `# SchedulerReconcileSnapshot ${snapshot.id}`,
    "",
    `Status: ${snapshot.status}`,
    `Change: ${snapshot.changeId}`,
    `SchedulerRun: ${snapshot.schedulerRunId}`,
    `RuntimeState: ${snapshot.schedulerRuntimeStateId}`,
    "",
    "## Summary",
    "",
    `- Waves: ${snapshot.waves.length}`,
    `- Claim intents: ${snapshot.claimIntents.length}`,
    `- Planned slot demand: ${snapshot.plannedSlotDemand}`,
    `- Max planned wave width: ${snapshot.maxPlannedWaveWidth}`,
    `- Blocked entries: ${snapshot.blockedCount}`,
    `- Warnings: ${snapshot.warningCount}`,
    `- Recovery checkpoint: ${snapshot.recoveryCheckpoint}`,
    "",
    "## Warnings",
    "",
    ...(snapshot.warnings.length ? snapshot.warnings.map((warning) => `- ${warning}`) : ["- none"]),
    "",
    "## Claim Intents",
    "",
    ...snapshot.claimIntents.map((claim) => [
      `### ${claim.claimIntentId}`,
      "",
      `- Status: ${claim.status}`,
      `- Planned worker key: ${claim.plannedWorkerKey}`,
      `- Node: ${claim.nodeId}`,
      `- Unit: ${claim.unitId}`,
      `- Wave: ${claim.waveIndex + 1}`,
      `- Planned slot demand: ${claim.plannedSlotDemand}`,
      `- Source scopes: ${claim.sourceScopes.join(", ") || "none"}`,
      `- Blocked reasons: ${claim.blockedReasons.length ? claim.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This reconcile snapshot is runtime shell evidence only. It does not claim workers, allocate slots, create runtime-continuity sidecars, start agents, create worktrees, create runs, or authorize execution.",
    "",
  ];
  return lines.join("\n");
}
