import type { SchedulerControlledStepEvidence, SchedulerIntegrationCandidate, SchedulerIntegrationCheckHandoff, SchedulerIntegrationOutcome, SchedulerReconcileSnapshot, SchedulerRunBlockedCloseout, SchedulerRunCompletion, SchedulerRuntimeClaimReservation, SchedulerRuntimeState, SchedulerRuntimeWorkerAudit, SchedulerRuntimeWorkerResult, SchedulerRuntimeWorkerReworkAudit, SchedulerRuntimeWorkerReworkPlan, SchedulerRuntimeWorkerReworkResult, SchedulerRuntimeWorkerReworkStart, SchedulerRuntimeWorkerReworkValidation, SchedulerRuntimeWorkerStart, SchedulerRuntimeWorkerValidation } from "./types.js";

export function renderSchedulerRuntimeStateMarkdown(state: SchedulerRuntimeState): string {
  const lines = [
    `# SchedulerRuntimeState ${state.id}`,
    "",
    `Status: ${state.status}`,
    `Change: ${state.changeId}`,
    `SchedulerRun: ${state.schedulerRunId}`,
    `SchedulerContract: ${state.schedulerContractId}`,
    "",
    "## Summary",
    "",
    `- Waves: ${state.waves.length}`,
    `- Claim intents: ${state.claimIntents.length}`,
    `- Planned slot demand: ${state.plannedSlotDemand}`,
    `- Max planned wave width: ${state.maxPlannedWaveWidth}`,
    `- Blocked entries: ${state.blockedCount}`,
    `- Last reconcile snapshot: ${state.lastReconcileSnapshotId ?? "none"}`,
    `- Last claim reservation: ${state.lastClaimReservationId ?? "none"}`,
    "",
    "## Waves",
    "",
    ...state.waves.map((wave) => [
      `### Wave ${wave.waveIndex + 1}`,
      "",
      `- Status: ${wave.status}`,
      `- Claim intents: ${wave.claimIntentIds.join(", ") || "none"}`,
      `- Candidate claims: ${wave.candidateCount}`,
      `- Blocked claims: ${wave.blockedCount}`,
      `- Planned slot demand: ${wave.plannedSlotDemand}`,
      `- Blocked reasons: ${wave.blockedReasons.length ? wave.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This runtime shell is not a parallel executor. It does not allocate WorkerLeases, create WorkerSessions, create TaskRuns, start agents, create worktrees, create runs, or authorize execution.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerControlledStepEvidenceMarkdown(step: SchedulerControlledStepEvidence): string {
  const lines = [
    `# SchedulerControlledStepEvidence ${step.id}`,
    "",
    `Status: ${step.status}`,
    `Change: ${step.changeId}`,
    `SchedulerRun: ${step.schedulerRunId ?? "none"}`,
    `Executed action: ${step.executedActionType}`,
    "",
    "## Summary",
    "",
    "- One human-confirmed concrete scheduler transition completed.",
    "- The controlled advance stopped after that one transition.",
    `- Post-step status: ${step.postStepHandoff.status}`,
    `- Needs reevaluation: ${step.postStepHandoff.needsReevaluation ? "yes" : "no"}`,
    `- Next candidate: ${step.postStepHandoff.nextConfirmationCandidate?.actionType ?? "none"}`,
    `- Warning: ${step.postStepEvidence.evaluationWarning ?? step.postStepEvidence.readinessWarning ?? step.postStepHandoff.warning ?? "none"}`,
    "",
    "## Concrete Result Summary",
    "",
    ...(step.controlledStepResultSummary
      ? Object.entries(step.controlledStepResultSummary).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : String(value)}`)
      : ["- none"]),
    "",
    "## Controlled Loop Turn Route",
    "",
    ...(step.controlledLoopTurnRouteSummary
      ? [
          `- Route posture: ${step.controlledLoopTurnRouteSummary.routePosture}`,
          `- Result kind: ${step.controlledLoopTurnRouteSummary.resultKind ?? "none"}`,
          `- Result id: ${step.controlledLoopTurnRouteSummary.resultId ?? "none"}`,
          `- Result status: ${step.controlledLoopTurnRouteSummary.resultStatus ?? "none"}`,
          `- Next candidate: ${step.controlledLoopTurnRouteSummary.nextCandidateActionType ?? "none"}`,
          `- Human gate required: ${step.controlledLoopTurnRouteSummary.humanGateRequired ? "yes" : "no"}`,
          `- Warning: ${step.controlledLoopTurnRouteSummary.warning ?? "none"}`,
          "- Execution from route summary: not authorized.",
        ]
      : ["- none"]),
    "",
    "## Controlled Loop Tick Contract",
    "",
    ...(step.controlledLoopTick
      ? [
          `- Authority: ${step.controlledLoopTick.authority}`,
          `- Observe: ${step.controlledLoopTick.observe.status} / ${step.controlledLoopTick.observe.goalLoopNextStepPacketId}`,
          `- Choose/check: ${step.controlledLoopTick.chooseCheck.status} / ${step.controlledLoopTick.chooseCheck.goalLoopGateReadinessPreflightId}`,
          `- Dispatch: ${step.controlledLoopTick.dispatch.status} / ${step.controlledLoopTick.dispatch.executedActionType}`,
          `- Reconcile: ${step.controlledLoopTick.reconcile.status} / ${step.controlledLoopTick.reconcile.goalLoopNextStepPacketId ?? "none"}`,
          `- Route/stop: ${step.controlledLoopTick.routeStop.routePosture} / ${step.controlledLoopTick.routeStop.stopReason}`,
          `- Human gate required: ${step.controlledLoopTick.routeStop.humanGateRequired ? "yes" : "no"}`,
          "- Execution from tick contract: not authorized.",
        ]
      : ["- none"]),
    "",
    "## Controlled Loop Continuation Readiness",
    "",
    ...(step.controlledLoopContinuationReadiness
      ? [
          `- Authority: ${step.controlledLoopContinuationReadiness.authority}`,
          `- Status: ${step.controlledLoopContinuationReadiness.status}`,
          `- Route posture: ${step.controlledLoopContinuationReadiness.routePosture}`,
          `- Next candidate: ${step.controlledLoopContinuationReadiness.nextCandidateActionType ?? "none"}`,
          `- Readiness evidence prepared: ${step.controlledLoopContinuationReadiness.readinessEvidencePrepared ? "yes" : "no"}`,
          `- Human confirmation still required: ${step.controlledLoopContinuationReadiness.humanConfirmationStillRequired ? "yes" : "no"}`,
          `- Reason: ${step.controlledLoopContinuationReadiness.reason}`,
          "- Execution from continuation readiness: not authorized.",
        ]
      : ["- none"]),
    "",
    "## Controlled Loop Iteration",
    "",
    ...(step.controlledLoopIteration
      ? [
          `- Authority: ${step.controlledLoopIteration.authority}`,
          `- Status: ${step.controlledLoopIteration.status}`,
          `- Executed action: ${step.controlledLoopIteration.executedActionType}`,
          `- Phases: observe ${step.controlledLoopIteration.observeStatus} / check ${step.controlledLoopIteration.chooseCheckStatus} / dispatch ${step.controlledLoopIteration.dispatchStatus} / reconcile ${step.controlledLoopIteration.reconcileStatus}`,
          `- Route posture: ${step.controlledLoopIteration.routePosture}`,
          `- Continuation readiness: ${step.controlledLoopIteration.continuationReadinessStatus}`,
          `- Next candidate: ${step.controlledLoopIteration.nextCandidateActionType ?? "none"}`,
          `- Human confirmation still required: ${step.controlledLoopIteration.humanConfirmationStillRequired ? "yes" : "no"}`,
          "- Execution from iteration summary: not authorized.",
        ]
      : ["- none"]),
    "",
    "## Current Transition Choice",
    "",
    ...(step.controlledLoopCurrentTransitionChoice
      ? [
          `- Authority: ${step.controlledLoopCurrentTransitionChoice.authority}`,
          `- Status: ${step.controlledLoopCurrentTransitionChoice.status}`,
          `- Selected action: ${step.controlledLoopCurrentTransitionChoice.selectedActionType}`,
          `- GoalLoopNextStepPacket: ${step.controlledLoopCurrentTransitionChoice.goalLoopNextStepPacketId}`,
          `- ControllerPolicy: ${step.controlledLoopCurrentTransitionChoice.goalLoopControllerPolicyId}`,
          `- GateReadinessPreflight: ${step.controlledLoopCurrentTransitionChoice.goalLoopGateReadinessPreflightId}`,
          `- Human confirmation still required: ${step.controlledLoopCurrentTransitionChoice.humanConfirmationStillRequired ? "yes" : "no"}`,
          "- Execution from current transition choice: not authorized.",
        ]
      : ["- none"]),
    "",
    "## Pre-step Evidence",
    "",
    `- GoalLoopDecision: ${step.preStepEvidence.goalLoopDecisionId}`,
    `- GoalLoopIteration: ${step.preStepEvidence.goalLoopIterationId}`,
    `- GoalLoopContinuationBrief: ${step.preStepEvidence.goalLoopContinuationBriefId}`,
    `- GoalLoopNextStepPacket: ${step.preStepEvidence.goalLoopNextStepPacketId}`,
    `- GoalLoopControllerPolicy: ${step.preStepEvidence.goalLoopControllerPolicyId}`,
    `- GoalLoopGateReadinessPreflight: ${step.preStepEvidence.goalLoopGateReadinessPreflightId}`,
    "",
    "## Post-step Evidence",
    "",
    `- GoalLoopDecision: ${step.postStepEvidence.goalLoopDecisionId ?? "none"}`,
    `- GoalLoopIteration: ${step.postStepEvidence.goalLoopIterationId ?? "none"}`,
    `- GoalLoopContinuationBrief: ${step.postStepEvidence.goalLoopContinuationBriefId ?? "none"}`,
    `- GoalLoopNextStepPacket: ${step.postStepEvidence.goalLoopNextStepPacketId ?? "none"}`,
    `- Recommended action: ${step.postStepEvidence.recommendedActionType ?? "none"}`,
    `- ControllerPolicy: ${step.postStepEvidence.goalLoopControllerPolicyId ?? "none"}`,
    `- GateReadinessPreflight: ${step.postStepEvidence.goalLoopGateReadinessPreflightId ?? "none"}`,
    "",
    "## Target Scope",
    "",
    ...Object.entries(step.targetScope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`),
    "",
    "## Forbidden Authority",
    "",
    "- Scheduler loop: not authorized.",
    "- Whole-wave dispatch: not authorized.",
    "- Slot allocation: not authorized.",
    "- Full parallel executor: not authorized.",
    "- Source mutation / apply / close / merge / remote landing / Harness evolution: not authorized.",
    "",
    "## Boundary",
    "",
    "This artifact is scheduler-runtime accounting evidence for one completed controlled Scheduler step. It does not authorize hidden continuation, a Scheduler loop, worker waves, source changes, apply, close, merge, remote landing, or Harness evolution. The next high-impact transition still requires the existing scoped human confirmation and ToolPolicy path.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeClaimReservationMarkdown(reservation: SchedulerRuntimeClaimReservation): string {
  const lines = [
    `# SchedulerRuntimeClaimReservation ${reservation.id}`,
    "",
    `Status: ${reservation.status}`,
    `Change: ${reservation.changeId}`,
    `SchedulerRun: ${reservation.schedulerRunId}`,
    `RuntimeState: ${reservation.schedulerRuntimeStateId}`,
    `ReconcileSnapshot: ${reservation.schedulerReconcileSnapshotId}`,
    "",
    "## Summary",
    "",
    `- Reserved claims: ${reservation.reservedCount}`,
    `- Blocked claims: ${reservation.blockedCount}`,
    `- Source locks: ${reservation.sourceLockCount}`,
    `- Supersedes reservation: ${reservation.supersedesReservationId ?? "none"}`,
    "",
    "## Waves",
    "",
    ...reservation.waves.map((wave) => [
      `### Wave ${wave.waveIndex + 1}`,
      "",
      `- Status: ${wave.status}`,
      `- Reservation intents: ${wave.reservationIntentIds.join(", ") || "none"}`,
      `- Reserved claims: ${wave.reservedCount}`,
      `- Blocked claims: ${wave.blockedCount}`,
      `- Planned slot demand: ${wave.plannedSlotDemand}`,
      `- Blocked reasons: ${wave.blockedReasons.length ? wave.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Reservation Intents",
    "",
    ...reservation.reservationIntents.map((intent) => [
      `### ${intent.reservationIntentId}`,
      "",
      `- Claim intent: ${intent.claimIntentId}`,
      `- Status: ${intent.status}`,
      `- Planned worker key: ${intent.plannedWorkerKey}`,
      `- Node: ${intent.nodeId}`,
      `- Unit: ${intent.unitId}`,
      `- Wave: ${intent.waveIndex + 1}`,
      `- Planned slot demand: ${intent.plannedSlotDemand}`,
      `- Source scopes: ${intent.sourceScopes.join(", ") || "none"}`,
      `- Blocked reasons: ${intent.blockedReasons.length ? intent.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Source Locks",
    "",
    ...(reservation.sourceLocks.length ? reservation.sourceLocks.map((lock) => [
      `### ${lock.scope}`,
      "",
      `- Status: ${lock.status}`,
      `- Wave: ${lock.waveIndex + 1}`,
      `- Reservation intents: ${lock.reservationIntentIds.join(", ") || "none"}`,
      `- Blocked reasons: ${lock.blockedReasons.length ? lock.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")) : ["- none", ""]),
    "## Boundary",
    "",
    "This claim reservation is runtime coordination evidence only. It is not a WorkerLease, WorkerSession, TaskRun, worktree, run, slot allocation, worker start, or execution authorization.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerReconcileSnapshotMarkdown(snapshot: SchedulerReconcileSnapshot): string {
  const lines = [
    `# SchedulerReconcileSnapshot ${snapshot.id}`,
    "",
    `Status: ${snapshot.status}`,
    `Change: ${snapshot.changeId}`,
    `SchedulerRun: ${snapshot.schedulerRunId}`,
    `RuntimeState: ${snapshot.schedulerRuntimeStateId}`,
    "",
    "## Summary",
    "",
    `- Waves: ${snapshot.waves.length}`,
    `- Claim intents: ${snapshot.claimIntents.length}`,
    `- Planned slot demand: ${snapshot.plannedSlotDemand}`,
    `- Max planned wave width: ${snapshot.maxPlannedWaveWidth}`,
    `- Blocked entries: ${snapshot.blockedCount}`,
    `- Warnings: ${snapshot.warningCount}`,
    `- Recovery checkpoint: ${snapshot.recoveryCheckpoint}`,
    "",
    "## Warnings",
    "",
    ...(snapshot.warnings.length ? snapshot.warnings.map((warning) => `- ${warning}`) : ["- none"]),
    "",
    "## Claim Intents",
    "",
    ...snapshot.claimIntents.map((claim) => [
      `### ${claim.claimIntentId}`,
      "",
      `- Status: ${claim.status}`,
      `- Planned worker key: ${claim.plannedWorkerKey}`,
      `- Node: ${claim.nodeId}`,
      `- Unit: ${claim.unitId}`,
      `- Wave: ${claim.waveIndex + 1}`,
      `- Planned slot demand: ${claim.plannedSlotDemand}`,
      `- Source scopes: ${claim.sourceScopes.join(", ") || "none"}`,
      `- Blocked reasons: ${claim.blockedReasons.length ? claim.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This reconcile snapshot is runtime shell evidence only. It does not claim workers, allocate slots, create runtime-continuity sidecars, start agents, create worktrees, create runs, or authorize execution.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerStartMarkdown(workerStart: SchedulerRuntimeWorkerStart): string {
  const lines = [
    `# SchedulerRuntimeWorkerStart ${workerStart.id}`,
    "",
    `Status: ${workerStart.status}`,
    `Change: ${workerStart.changeId}`,
    `SchedulerRun: ${workerStart.schedulerRunId}`,
    `ClaimReservation: ${workerStart.schedulerClaimReservationId}`,
    "",
    "## Worker",
    "",
    `- Reservation intent: ${workerStart.reservationIntentId}`,
    `- Claim intent: ${workerStart.claimIntentId}`,
    `- Planned worker key: ${workerStart.plannedWorkerKey}`,
    `- Node: ${workerStart.nodeId}`,
    `- Unit: ${workerStart.unitId}`,
    `- Wave: ${workerStart.waveIndex + 1}`,
    `- Stage: ${workerStart.stage}`,
    `- Task: ${workerStart.taskId}`,
    `- TaskRun: ${workerStart.taskRunId}`,
    `- WorkerLease: ${workerStart.workerLeaseId}`,
    `- TaskRun role: ${workerStart.taskRunRoleId}`,
    `- Agent role: ${workerStart.agentRoleId}`,
    `- Worktree: ${workerStart.worktreeId ?? "none"}`,
    `- Code run: ${workerStart.runId ?? "none"}`,
    ...(workerStart.failureReason ? [`- Failure: ${workerStart.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This worker-start evidence records one scheduler claim's coder-stage start only. It does not start a full wave, validation, audit, bounded rework, scheduler loop, slot allocator, child Change, WorkflowRun, TaskQueueRun, or AgentTask.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerResultMarkdown(result: SchedulerRuntimeWorkerResult): string {
  const lines = [
    `# SchedulerRuntimeWorkerResult ${result.id}`,
    "",
    `Status: ${result.status}`,
    `Change: ${result.changeId}`,
    `SchedulerRun: ${result.schedulerRunId}`,
    `WorkerStart: ${result.schedulerWorkerStartId}`,
    `ClaimReservation: ${result.schedulerClaimReservationId}`,
    "",
    "## Worker Result",
    "",
    `- Reservation intent: ${result.reservationIntentId}`,
    `- Claim intent: ${result.claimIntentId}`,
    `- Planned worker key: ${result.plannedWorkerKey}`,
    `- Node: ${result.nodeId}`,
    `- Unit: ${result.unitId}`,
    `- Wave: ${result.waveIndex + 1}`,
    `- Stage: ${result.stage}`,
    `- Task: ${result.taskId}`,
    `- TaskRun: ${result.taskRunId}`,
    `- TaskRun status: ${result.taskRunStatus}`,
    `- WorkerLease: ${result.workerLeaseId}`,
    `- WorkerLease status: ${result.workerLeaseStatus}`,
    `- Agent role: ${result.agentRoleId}`,
    `- Worktree: ${result.worktreeId ?? "none"}`,
    `- Code run: ${result.runId ?? "none"}`,
    `- Code run status: ${result.runStatus ?? "none"}`,
    ...(result.failureReason ? [`- Failure: ${result.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This worker-result evidence reconciles one scheduler coder-stage worker only. Coder success means evidence-ready for later validation/audit; it is not task completion, source apply, whole-wave dispatch, scheduler loop, or parallel executor authorization.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerValidationMarkdown(validation: SchedulerRuntimeWorkerValidation): string {
  const lines = [
    `# SchedulerRuntimeWorkerValidation ${validation.id}`,
    "",
    `Status: ${validation.status}`,
    `Change: ${validation.changeId}`,
    `SchedulerRun: ${validation.schedulerRunId}`,
    `WorkerResult: ${validation.schedulerWorkerResultId}`,
    `WorkerStart: ${validation.schedulerWorkerStartId}`,
    `ClaimReservation: ${validation.schedulerClaimReservationId}`,
    "",
    "## Worker Validation",
    "",
    `- Reservation intent: ${validation.reservationIntentId}`,
    `- Claim intent: ${validation.claimIntentId}`,
    `- Planned worker key: ${validation.plannedWorkerKey}`,
    `- Node: ${validation.nodeId}`,
    `- Unit: ${validation.unitId}`,
    `- Wave: ${validation.waveIndex + 1}`,
    `- Stage: ${validation.stage}`,
    `- Task: ${validation.taskId}`,
    `- TaskRun: ${validation.taskRunId}`,
    `- TaskRun status: ${validation.taskRunStatus}`,
    `- WorkerLease: ${validation.workerLeaseId}`,
    `- Worktree: ${validation.worktreeId}`,
    `- Code run: ${validation.codeRunId}`,
    `- Validation run: ${validation.validationRunId}`,
    `- Validation status: ${validation.validationStatus}`,
    ...(validation.failureReason ? [`- Failure: ${validation.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This worker-validation evidence validates one scheduler coder-stage worker worktree only. Passed validation is not task completion; audit remains a later gate. It does not start audit, bounded rework, a next worker, whole-wave dispatch, scheduler loop, apply, or merge.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerAuditMarkdown(audit: SchedulerRuntimeWorkerAudit): string {
  const lines = [
    `# SchedulerRuntimeWorkerAudit ${audit.id}`,
    "",
    `Status: ${audit.status}`,
    `Change: ${audit.changeId}`,
    `SchedulerRun: ${audit.schedulerRunId}`,
    `WorkerValidation: ${audit.schedulerWorkerValidationId}`,
    `WorkerResult: ${audit.schedulerWorkerResultId}`,
    `WorkerStart: ${audit.schedulerWorkerStartId}`,
    `ClaimReservation: ${audit.schedulerClaimReservationId}`,
    "",
    "## Worker Audit",
    "",
    `- Reservation intent: ${audit.reservationIntentId}`,
    `- Claim intent: ${audit.claimIntentId}`,
    `- Planned worker key: ${audit.plannedWorkerKey}`,
    `- Node: ${audit.nodeId}`,
    `- Unit: ${audit.unitId}`,
    `- Wave: ${audit.waveIndex + 1}`,
    `- Stage: ${audit.stage}`,
    `- Task: ${audit.taskId}`,
    `- TaskRun: ${audit.taskRunId}`,
    `- TaskRun status: ${audit.taskRunStatus}`,
    `- WorkerLease: ${audit.workerLeaseId}`,
    `- Worktree: ${audit.worktreeId}`,
    `- Code run: ${audit.codeRunId}`,
    `- Validation run: ${audit.validationRunId}`,
    `- Validation status: ${audit.validationStatus}`,
    `- Audit run: ${audit.auditRunId}`,
    `- Audit status: ${audit.auditStatus}`,
    ...(audit.failureReason ? [`- Failure: ${audit.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This worker-audit evidence audits one scheduler coder-stage worker worktree only. Approved audit may complete that TaskRun; blocked or failed audit only blocks the current worker path. It does not start rework, a next worker, whole-wave dispatch, scheduler loop, apply, or merge.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerReworkPlanMarkdown(plan: SchedulerRuntimeWorkerReworkPlan): string {
  const lines = [
    `# SchedulerRuntimeWorkerReworkPlan ${plan.id}`,
    "",
    `Status: ${plan.status}`,
    `Change: ${plan.changeId}`,
    `SchedulerRun: ${plan.schedulerRunId}`,
    `Blocking source: ${plan.blockingSource}`,
    `WorkerValidation: ${plan.schedulerWorkerValidationId}`,
    `WorkerAudit: ${plan.schedulerWorkerAuditId ?? "none"}`,
    `ClaimReservation: ${plan.schedulerClaimReservationId}`,
    "",
    "## Rework Intent",
    "",
    `- Reason: ${plan.reworkReason}`,
    `- Reservation intent: ${plan.reservationIntentId}`,
    `- Claim intent: ${plan.claimIntentId}`,
    `- Planned worker key: ${plan.plannedWorkerKey}`,
    `- Node: ${plan.nodeId}`,
    `- Unit: ${plan.unitId}`,
    `- Wave: ${plan.waveIndex + 1}`,
    `- Stage: ${plan.stage}`,
    `- Task: ${plan.taskId}`,
    `- Current TaskRun: ${plan.taskRunId}`,
    `- Current TaskRun status: ${plan.taskRunStatus}`,
    `- WorkerLease: ${plan.workerLeaseId}`,
    `- Target worktree: ${plan.targetWorktreeId}`,
    `- Target code run: ${plan.targetCodeRunId}`,
    `- Validation run: ${plan.validationRunId}`,
    `- Validation status: ${plan.validationStatus}`,
    `- Audit run: ${plan.auditRunId ?? "none"}`,
    `- Audit status: ${plan.auditStatus ?? "none"}`,
    `- Future code gate: ${plan.futureCodeGateMode}`,
    "",
    "## Recovery Key Inputs",
    "",
    ...(plan.recoveryKeyInputs.length ? plan.recoveryKeyInputs.map((item) => `- ${item}`) : ["- none"]),
    "",
    "## Boundary",
    "",
    "This rework plan is non-executing scheduler evidence. It does not start rework, call startCodeRun(), create TaskRuns, WorkerLeases, WorkerSessions, RuntimeWorkspaces, EventSources, worktrees, runs, AgentTasks, WorkflowRuns, TaskQueueRuns, child Changes, next workers, whole-wave dispatch, apply, or merge.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerReworkStartMarkdown(start: SchedulerRuntimeWorkerReworkStart): string {
  const lines = [
    `# SchedulerRuntimeWorkerReworkStart ${start.id}`,
    "",
    `Status: ${start.status}`,
    `Change: ${start.changeId}`,
    `SchedulerRun: ${start.schedulerRunId}`,
    `ReworkPlan: ${start.schedulerWorkerReworkPlanId}`,
    `ClaimReservation: ${start.schedulerClaimReservationId}`,
    "",
    "## Rework Start",
    "",
    `- Reservation intent: ${start.reservationIntentId}`,
    `- Claim intent: ${start.claimIntentId}`,
    `- Planned worker key: ${start.plannedWorkerKey}`,
    `- Node: ${start.nodeId}`,
    `- Unit: ${start.unitId}`,
    `- Wave: ${start.waveIndex + 1}`,
    `- Stage: ${start.stage}`,
    `- Task: ${start.taskId}`,
    `- Original TaskRun: ${start.originalTaskRunId}`,
    `- Original WorkerLease: ${start.originalWorkerLeaseId}`,
    `- Rework TaskRun: ${start.reworkTaskRunId}`,
    `- Rework WorkerLease: ${start.reworkWorkerLeaseId}`,
    `- TaskRun role: ${start.taskRunRoleId}`,
    `- Agent role: ${start.agentRoleId}`,
    `- Worktree: ${start.worktreeId}`,
    `- Original code run: ${start.originalCodeRunId}`,
    `- Rework code run: ${start.reworkRunId ?? "none"}`,
    ...(start.failureReason ? [`- Failure: ${start.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This rework-start evidence records one same-worktree scheduler rework-coder start only. It does not create a new worktree, validate or audit the rework result, reconcile the rework result, start another worker, run a whole wave, run IntegrationCheck, apply, merge, create child Changes, or become a full parallel executor.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerReworkResultMarkdown(result: SchedulerRuntimeWorkerReworkResult): string {
  const lines = [
    `# SchedulerRuntimeWorkerReworkResult ${result.id}`,
    "",
    `Status: ${result.status}`,
    `Change: ${result.changeId}`,
    `SchedulerRun: ${result.schedulerRunId}`,
    `ReworkStart: ${result.schedulerWorkerReworkStartId}`,
    `ReworkPlan: ${result.schedulerWorkerReworkPlanId}`,
    `ClaimReservation: ${result.schedulerClaimReservationId}`,
    "",
    "## Rework Result",
    "",
    `- Reservation intent: ${result.reservationIntentId}`,
    `- Claim intent: ${result.claimIntentId}`,
    `- Planned worker key: ${result.plannedWorkerKey}`,
    `- Node: ${result.nodeId}`,
    `- Unit: ${result.unitId}`,
    `- Wave: ${result.waveIndex + 1}`,
    `- Stage: ${result.stage}`,
    `- Task: ${result.taskId}`,
    `- Original TaskRun: ${result.originalTaskRunId}`,
    `- Original WorkerLease: ${result.originalWorkerLeaseId}`,
    `- Original code run: ${result.originalCodeRunId}`,
    `- Rework TaskRun: ${result.reworkTaskRunId}`,
    `- Rework TaskRun status: ${result.taskRunStatus}`,
    `- Rework WorkerLease: ${result.reworkWorkerLeaseId}`,
    `- Rework WorkerLease status: ${result.workerLeaseStatus}`,
    `- Agent role: ${result.agentRoleId}`,
    `- Worktree: ${result.worktreeId}`,
    `- Rework code run: ${result.reworkRunId ?? "none"}`,
    `- Rework code run status: ${result.reworkRunStatus ?? "none"}`,
    ...(result.failureReason ? [`- Failure: ${result.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This rework-result evidence reconciles one same-worktree scheduler rework-coder run only. Rework success means evidence-ready for later rework validation/audit; it is not task completion, source apply, next-worker dispatch, whole-wave dispatch, scheduler loop, or parallel executor authorization.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerReworkValidationMarkdown(validation: SchedulerRuntimeWorkerReworkValidation): string {
  const lines = [
    `# SchedulerRuntimeWorkerReworkValidation ${validation.id}`,
    "",
    `Status: ${validation.status}`,
    `Change: ${validation.changeId}`,
    `SchedulerRun: ${validation.schedulerRunId}`,
    `ReworkResult: ${validation.schedulerWorkerReworkResultId}`,
    `ReworkStart: ${validation.schedulerWorkerReworkStartId}`,
    `ReworkPlan: ${validation.schedulerWorkerReworkPlanId}`,
    `ClaimReservation: ${validation.schedulerClaimReservationId}`,
    "",
    "## Rework Validation",
    "",
    `- Reservation intent: ${validation.reservationIntentId}`,
    `- Claim intent: ${validation.claimIntentId}`,
    `- Planned worker key: ${validation.plannedWorkerKey}`,
    `- Node: ${validation.nodeId}`,
    `- Unit: ${validation.unitId}`,
    `- Wave: ${validation.waveIndex + 1}`,
    `- Stage: ${validation.stage}`,
    `- Task: ${validation.taskId}`,
    `- Original TaskRun: ${validation.originalTaskRunId}`,
    `- Original WorkerLease: ${validation.originalWorkerLeaseId}`,
    `- Original code run: ${validation.originalCodeRunId}`,
    `- Rework TaskRun: ${validation.reworkTaskRunId}`,
    `- Rework TaskRun status: ${validation.taskRunStatus}`,
    `- Rework WorkerLease: ${validation.reworkWorkerLeaseId}`,
    `- Worktree: ${validation.worktreeId}`,
    `- Rework code run: ${validation.reworkRunId}`,
    `- Validation run: ${validation.validationRunId}`,
    `- Validation status: ${validation.validationStatus}`,
    ...(validation.failureReason ? [`- Failure: ${validation.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This rework-validation evidence validates one same-worktree scheduler rework result only. Passing validation is not task completion; rework audit remains required before the scheduler task can complete. It does not start audit, another rework, another worker, a whole wave, IntegrationCheck, apply, merge, child Changes, a scheduler loop, or a parallel executor.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRuntimeWorkerReworkAuditMarkdown(audit: SchedulerRuntimeWorkerReworkAudit): string {
  const lines = [
    `# SchedulerRuntimeWorkerReworkAudit ${audit.id}`,
    "",
    `Status: ${audit.status}`,
    `Change: ${audit.changeId}`,
    `SchedulerRun: ${audit.schedulerRunId}`,
    `ReworkValidation: ${audit.schedulerWorkerReworkValidationId}`,
    `ReworkResult: ${audit.schedulerWorkerReworkResultId}`,
    `ReworkStart: ${audit.schedulerWorkerReworkStartId}`,
    `ReworkPlan: ${audit.schedulerWorkerReworkPlanId}`,
    `ClaimReservation: ${audit.schedulerClaimReservationId}`,
    "",
    "## Rework Audit",
    "",
    `- Reservation intent: ${audit.reservationIntentId}`,
    `- Claim intent: ${audit.claimIntentId}`,
    `- Planned worker key: ${audit.plannedWorkerKey}`,
    `- Node: ${audit.nodeId}`,
    `- Unit: ${audit.unitId}`,
    `- Wave: ${audit.waveIndex + 1}`,
    `- Stage: ${audit.stage}`,
    `- Task: ${audit.taskId}`,
    `- Original TaskRun: ${audit.originalTaskRunId}`,
    `- Original WorkerLease: ${audit.originalWorkerLeaseId}`,
    `- Original code run: ${audit.originalCodeRunId}`,
    `- Rework TaskRun: ${audit.reworkTaskRunId}`,
    `- Rework TaskRun status: ${audit.taskRunStatus}`,
    `- Rework WorkerLease: ${audit.reworkWorkerLeaseId}`,
    `- Worktree: ${audit.worktreeId}`,
    `- Rework code run: ${audit.reworkRunId}`,
    `- Validation run: ${audit.validationRunId}`,
    `- Validation status: ${audit.validationStatus}`,
    `- Audit run: ${audit.auditRunId}`,
    `- Audit status: ${audit.auditStatus}`,
    ...(audit.failureReason ? [`- Failure: ${audit.failureReason}`] : []),
    "",
    "## Boundary",
    "",
    "This rework-audit evidence audits one same-worktree scheduler rework result only. Approved audit can complete the rework TaskRun; blocked or failed audit blocks only the current rework path. It does not start another rework, another worker, a whole wave, IntegrationCheck, apply, merge, child Changes, a scheduler loop, or a parallel executor.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerIntegrationCandidateMarkdown(candidate: SchedulerIntegrationCandidate): string {
  const lines = [
    `# SchedulerIntegrationCandidate ${candidate.id}`,
    "",
    `Status: ${candidate.status}`,
    `Change: ${candidate.changeId}`,
    `SchedulerRun: ${candidate.schedulerRunId}`,
    `ClaimReservation: ${candidate.schedulerClaimReservationId}`,
    "",
    "## Summary",
    "",
    `- Ready targets: ${candidate.readyCount}`,
    `- Blocked outputs: ${candidate.blockedCount}`,
    `- Ready worktrees: ${candidate.readyWorktreeIds.join(", ") || "none"}`,
    `- Waiting reason: ${candidate.waitingReason ?? "none"}`,
    "",
    "## Ready Targets",
    "",
    ...(candidate.readyTargets.length ? candidate.readyTargets.map((target) => [
      `### ${target.worktreeId}`,
      "",
      `- Diff hash: ${target.worktreeDiffHash}`,
      `- Validation run: ${target.validationRunId}`,
      `- Audit run: ${target.auditRunId}`,
      `- Source HEAD: ${target.sourceHead ?? "unknown"}`,
      "",
    ].join("\n")) : ["- none", ""]),
    "## Outputs",
    "",
    ...candidate.outputs.map((output) => [
      `### ${output.outputId}`,
      "",
      `- Kind: ${output.kind}`,
      `- Status: ${output.status}`,
      `- Claim intent: ${output.claimIntentId ?? "none"}`,
      `- Worktree: ${output.worktreeId ?? "none"}`,
      `- Readiness: ${output.readinessKind ?? "none"}${output.readinessMessage ? ` (${output.readinessMessage})` : ""}`,
      `- Blocking reasons: ${output.blockingReasons.length ? output.blockingReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This scheduler integration candidate bridges audited scheduler worker output into the existing IntegrationCheck/apply readiness chain. It is not IntegrationCheck, apply authorization, merge authorization, next-worker dispatch, whole-wave dispatch, or a parallel executor.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerIntegrationCheckHandoffMarkdown(handoff: SchedulerIntegrationCheckHandoff): string {
  const lines = [
    `# SchedulerIntegrationCheckHandoff ${handoff.id}`,
    "",
    `Status: ${handoff.status}`,
    `Change: ${handoff.changeId}`,
    `SchedulerRun: ${handoff.schedulerRunId}`,
    `IntegrationCandidate: ${handoff.schedulerIntegrationCandidateId}`,
    `IntegrationCheck: ${handoff.integrationCheckId} (${handoff.integrationCheckStatus})`,
    "",
    "## Summary",
    "",
    `- Ready targets: ${handoff.readyTargets.length}`,
    `- Ready worktrees: ${handoff.readyWorktreeIds.join(", ") || "none"}`,
    `- Result target worktrees: ${handoff.resultTargetWorktreeIds.join(", ") || "none"}`,
    "",
    "## Ready Targets",
    "",
    ...(handoff.readyTargets.length ? handoff.readyTargets.map((target) => [
      `### ${target.worktreeId}`,
      "",
      `- Diff hash: ${target.worktreeDiffHash}`,
      `- Validation run: ${target.validationRunId}`,
      `- Audit run: ${target.auditRunId}`,
      `- Source HEAD: ${target.sourceHead ?? "unknown"}`,
      "",
    ].join("\n")) : ["- none", ""]),
    "## Boundary",
    "",
    "This handoff records that scheduler-owned ready outputs were explicitly passed to the existing IntegrationCheck gate. It does not apply source changes, discard worktrees, prepare landing, create PRs, merge, start another worker, or authorize the full parallel executor.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerIntegrationOutcomeMarkdown(outcome: SchedulerIntegrationOutcome): string {
  const lines = [
    `# SchedulerIntegrationOutcome ${outcome.id}`,
    "",
    `Status: ${outcome.status}`,
    `Change: ${outcome.changeId}`,
    `SchedulerRun: ${outcome.schedulerRunId}`,
    `IntegrationCheckHandoff: ${outcome.schedulerIntegrationCheckHandoffId}`,
    `IntegrationCheck: ${outcome.integrationCheckId} (${outcome.integrationCheckStatus})`,
    "",
    "## Summary",
    "",
    `- Outcome reason: ${outcome.outcomeReason}`,
    `- Ready worktrees: ${outcome.readyWorktreeIds.join(", ") || "none"}`,
    `- Result target worktrees: ${outcome.resultTargetWorktreeIds.join(", ") || "none"}`,
    `- Applied at: ${outcome.appliedAt ?? "none"}`,
    `- Latest artifact hash: ${outcome.latestArtifactHash ?? "none"}`,
    "",
    "## Targets",
    "",
    ...(outcome.targets.length ? outcome.targets.map((target) => [
      `### ${target.worktreeId}`,
      "",
      `- Change: ${target.changeId}`,
      `- Diff hash: ${target.diffHash}`,
      `- Source HEAD: ${target.sourceHead ?? "unknown"}`,
      `- Applied: ${target.applied ? "yes" : "no"}`,
      `- Applied at: ${target.appliedAt ?? "none"}`,
      `- Applied commit: ${target.appliedCommit ?? "none"}`,
      "",
    ].join("\n")) : ["- none", ""]),
    "## Boundary",
    "",
    "This scheduler integration outcome is runtime accounting evidence only. It does not run IntegrationCheck, apply source changes, discard worktrees, prepare landing, create PRs, merge, start another worker, or authorize the full parallel executor.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRunCompletionMarkdown(completion: SchedulerRunCompletion): string {
  const lines = [
    `# SchedulerRunCompletion ${completion.id}`,
    "",
    `Status: ${completion.status}`,
    `Change: ${completion.changeId}`,
    `SchedulerRun: ${completion.schedulerRunId}`,
    `SchedulerIntegrationOutcome: ${completion.schedulerIntegrationOutcomeId}`,
    `IntegrationCheck: ${completion.integrationCheckId} (${completion.integrationCheckStatus})`,
    "",
    "## Summary",
    "",
    `- Outcome status: ${completion.outcomeStatus}`,
    `- Outcome reason: ${completion.outcomeReason}`,
    `- Ready worktrees: ${completion.readyWorktreeIds.join(", ") || "none"}`,
    `- Result target worktrees: ${completion.resultTargetWorktreeIds.join(", ") || "none"}`,
    "",
    "## Lineage",
    "",
    `- Runtime state: ${completion.schedulerRuntimeStateId}`,
    `- Reconcile snapshot: ${completion.schedulerReconcileSnapshotId}`,
    `- Claim reservation: ${completion.schedulerClaimReservationId}`,
    `- Integration candidate: ${completion.schedulerIntegrationCandidateId}`,
    `- IntegrationCheck handoff: ${completion.schedulerIntegrationCheckHandoffId}`,
    `- SchedulerContract: ${completion.schedulerContractId}`,
    `- Dispatch dry-run: ${completion.schedulerDispatchDryRunId}`,
    `- Worker plan: ${completion.schedulerWorkerPlanId}`,
    `- Claim/reconcile plan: ${completion.schedulerClaimReconcilePlanId}`,
    `- Launch preflight: ${completion.schedulerLaunchPreflightId}`,
    "",
    "## Boundary",
    "",
    "This completion evidence only records that the SchedulerRun reached a terminal projection after existing IntegrationCheck/apply/discard outcome evidence. It does not run IntegrationCheck, apply source changes, discard worktrees, start another worker, dispatch waves, allocate slots, create child Changes, prepare landing, create PRs, merge, or authorize the full parallel executor.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRunBlockedCloseoutMarkdown(closeout: SchedulerRunBlockedCloseout): string {
  const lines = [
    `# SchedulerRunBlockedCloseout ${closeout.id}`,
    "",
    `Status: ${closeout.status}`,
    `Reason: ${closeout.reason}`,
    `Change: ${closeout.changeId}`,
    `SchedulerRun: ${closeout.schedulerRunId}`,
    `IntegrationCandidate: ${closeout.schedulerIntegrationCandidateId}`,
    "",
    "## Summary",
    "",
    `- Closeout reason: ${closeout.closeoutReason}`,
    `- Ready targets: ${closeout.readyCount}`,
    `- Ready worktrees: ${closeout.readyWorktreeIds.join(", ") || "none"}`,
    `- Blocked outputs: ${closeout.blockedCount}`,
    `- Unstarted reserved intents: ${closeout.unstartedReservedIntentIds.join(", ") || "none"}`,
    "",
    "## Blocked Reasons",
    "",
    ...(closeout.blockedReasons.length ? closeout.blockedReasons.map((reason) => `- ${reason}`) : ["- none"]),
    "",
    "## Lineage",
    "",
    `- Runtime state: ${closeout.schedulerRuntimeStateId}`,
    `- Reconcile snapshot: ${closeout.schedulerReconcileSnapshotId}`,
    `- Claim reservation: ${closeout.schedulerClaimReservationId}`,
    `- SchedulerContract: ${closeout.schedulerContractId}`,
    `- Dispatch dry-run: ${closeout.schedulerDispatchDryRunId}`,
    `- Worker plan: ${closeout.schedulerWorkerPlanId}`,
    `- Claim/reconcile plan: ${closeout.schedulerClaimReconcilePlanId}`,
    `- Launch preflight: ${closeout.schedulerLaunchPreflightId}`,
    "",
    "## Boundary",
    "",
    "This closeout evidence records that the SchedulerRun cannot proceed to IntegrationCheck and has no legal next-worker continuation. It does not run IntegrationCheck, apply or discard source changes, start workers, dispatch waves, allocate slots, create child Changes, create worktrees or runs, prepare landing, create PRs, merge, or authorize the full parallel executor.",
    "",
  ];
  return lines.join("\n");
}
