import { z } from "zod";
import type { SchedulerReconcileSnapshot, SchedulerRuntimeClaimReservation, SchedulerRuntimeEvent, SchedulerRuntimeState, SchedulerRuntimeWorkerResult, SchedulerRuntimeWorkerStart, SchedulerRuntimeWorkerValidation } from "./types.js";

const claimIntentStateSchema = z.object({
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  status: z.enum(["pending", "blocked"]),
  plannedSlotDemand: z.number(),
  sourceScopes: z.array(z.string()),
  blockedReasons: z.array(z.string()),
});

const waveStateSchema = z.object({
  waveIndex: z.number(),
  claimIntentIds: z.array(z.string()),
  candidateCount: z.number(),
  blockedCount: z.number(),
  plannedSlotDemand: z.number(),
  status: z.enum(["pending", "blocked"]),
  blockedReasons: z.array(z.string()),
});

export const schedulerRuntimeStateSchema: z.ZodType<SchedulerRuntimeState> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["initialized", "blocked"]),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  decompositionPlanId: z.string(),
  readinessManifestId: z.string(),
  claimIntents: z.array(claimIntentStateSchema),
  waves: z.array(waveStateSchema),
  plannedSlotDemand: z.number(),
  maxPlannedWaveWidth: z.number(),
  blockedCount: z.number(),
  lastReconcileSnapshotId: z.string().optional(),
  lastClaimReservationId: z.string().optional(),
  lastClaimReservationSnapshotId: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  eventsArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeEventSchema: z.ZodType<SchedulerRuntimeEvent> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  schedulerRunId: z.string(),
  changeId: z.string(),
  type: z.enum([
    "scheduler-runtime.initialized",
    "scheduler-runtime.reconciled",
    "scheduler-runtime.blocked",
    "scheduler-runtime.claim-reserved",
    "scheduler-runtime.claim-blocked",
    "scheduler-runtime.claim-reservation.superseded",
    "scheduler-runtime.worker-started",
    "scheduler-runtime.worker-start-failed",
    "scheduler-runtime.worker-result-ready",
    "scheduler-runtime.worker-result-failed",
    "scheduler-runtime.worker-validation-passed",
    "scheduler-runtime.worker-validation-failed",
  ]),
  timestamp: z.string(),
  status: z.enum(["initialized", "blocked"]).optional(),
  summary: z.string().optional(),
  artifactRefs: z.array(z.string()).optional(),
  payload: z.record(z.unknown()).optional(),
});

export const schedulerReconcileSnapshotSchema: z.ZodType<SchedulerReconcileSnapshot> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["generated", "blocked"]),
  schedulerRuntimeStateId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  claimIntents: z.array(claimIntentStateSchema),
  waves: z.array(waveStateSchema),
  plannedSlotDemand: z.number(),
  maxPlannedWaveWidth: z.number(),
  blockedCount: z.number(),
  warningCount: z.number(),
  warnings: z.array(z.string()),
  recoveryCheckpoint: z.string(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
});

const claimReservationIntentSchema = z.object({
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  status: z.enum(["reserved", "blocked"]),
  plannedSlotDemand: z.number(),
  sourceScopes: z.array(z.string()),
  blockedReasons: z.array(z.string()),
});

const sourceLockReservationSchema = z.object({
  scope: z.string(),
  waveIndex: z.number(),
  reservationIntentIds: z.array(z.string()),
  status: z.enum(["reserved", "blocked"]),
  blockedReasons: z.array(z.string()),
});

const waveReservationSchema = z.object({
  waveIndex: z.number(),
  reservationIntentIds: z.array(z.string()),
  reservedCount: z.number(),
  blockedCount: z.number(),
  plannedSlotDemand: z.number(),
  status: z.enum(["reserved", "blocked"]),
  blockedReasons: z.array(z.string()),
});

export const schedulerRuntimeClaimReservationSchema: z.ZodType<SchedulerRuntimeClaimReservation> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["reserved", "blocked", "rejected"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntents: z.array(claimReservationIntentSchema),
  waves: z.array(waveReservationSchema),
  sourceLocks: z.array(sourceLockReservationSchema),
  reservedCount: z.number(),
  blockedCount: z.number(),
  sourceLockCount: z.number(),
  supersedesReservationId: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
});

export const schedulerRuntimeWorkerStartSchema: z.ZodType<SchedulerRuntimeWorkerStart> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["started", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("coder"),
  taskId: z.string(),
  taskRunId: z.string(),
  workerLeaseId: z.string(),
  taskRunRoleId: z.string(),
  agentRoleId: z.string(),
  worktreeId: z.string().optional(),
  runId: z.string().optional(),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeWorkerResultSchema: z.ZodType<SchedulerRuntimeWorkerResult> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["evidence-ready", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerWorkerStartId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("coder"),
  taskId: z.string(),
  taskRunId: z.string(),
  workerLeaseId: z.string(),
  taskRunStatus: z.string(),
  workerLeaseStatus: z.string(),
  agentRoleId: z.string(),
  worktreeId: z.string().optional(),
  runId: z.string().optional(),
  runStatus: z.string().optional(),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeWorkerValidationSchema: z.ZodType<SchedulerRuntimeWorkerValidation> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["passed", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerWorkerStartId: z.string(),
  schedulerWorkerResultId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("validation"),
  taskId: z.string(),
  taskRunId: z.string(),
  workerLeaseId: z.string(),
  taskRunStatus: z.string(),
  worktreeId: z.string(),
  codeRunId: z.string(),
  validationRunId: z.string(),
  validationStatus: z.string(),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
