import { z } from "zod";
import type { SchedulerControlledStepEvidence, SchedulerIntegrationCandidate, SchedulerIntegrationCheckHandoff, SchedulerIntegrationOutcome, SchedulerReconcileSnapshot, SchedulerRunBlockedCloseout, SchedulerRunCompletion, SchedulerRuntimeClaimReservation, SchedulerRuntimeEvent, SchedulerRuntimeState, SchedulerRuntimeWorkerAudit, SchedulerRuntimeWorkerResult, SchedulerRuntimeWorkerReworkAudit, SchedulerRuntimeWorkerReworkPlan, SchedulerRuntimeWorkerReworkResult, SchedulerRuntimeWorkerReworkStart, SchedulerRuntimeWorkerReworkValidation, SchedulerRuntimeWorkerStart, SchedulerRuntimeWorkerValidation } from "./types.js";

const claimIntentStateSchema = z.object({
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  status: z.enum(["pending", "blocked"]),
  plannedSlotDemand: z.number(),
  sourceScopes: z.array(z.string()),
  blockedReasons: z.array(z.string()),
});

const waveStateSchema = z.object({
  waveIndex: z.number(),
  claimIntentIds: z.array(z.string()),
  candidateCount: z.number(),
  blockedCount: z.number(),
  plannedSlotDemand: z.number(),
  status: z.enum(["pending", "blocked"]),
  blockedReasons: z.array(z.string()),
});

export const schedulerRuntimeStateSchema: z.ZodType<SchedulerRuntimeState> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["initialized", "blocked"]),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  decompositionPlanId: z.string(),
  readinessManifestId: z.string(),
  claimIntents: z.array(claimIntentStateSchema),
  waves: z.array(waveStateSchema),
  plannedSlotDemand: z.number(),
  maxPlannedWaveWidth: z.number(),
  blockedCount: z.number(),
  lastReconcileSnapshotId: z.string().optional(),
  lastClaimReservationId: z.string().optional(),
  lastClaimReservationSnapshotId: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  eventsArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeEventSchema: z.ZodType<SchedulerRuntimeEvent> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  schedulerRunId: z.string(),
  changeId: z.string(),
  type: z.enum([
    "scheduler-runtime.initialized",
    "scheduler-runtime.reconciled",
    "scheduler-runtime.blocked",
    "scheduler-runtime.claim-reserved",
    "scheduler-runtime.claim-blocked",
    "scheduler-runtime.claim-reservation.superseded",
    "scheduler-runtime.worker-started",
    "scheduler-runtime.worker-start-failed",
    "scheduler-runtime.worker-result-ready",
    "scheduler-runtime.worker-result-failed",
    "scheduler-runtime.worker-validation-passed",
    "scheduler-runtime.worker-validation-failed",
    "scheduler-runtime.worker-audit-approved",
    "scheduler-runtime.worker-audit-blocked",
    "scheduler-runtime.worker-audit-failed",
    "scheduler-runtime.worker-rework-planned",
    "scheduler-runtime.worker-rework-started",
    "scheduler-runtime.worker-rework-start-failed",
    "scheduler-runtime.worker-rework-result-ready",
    "scheduler-runtime.worker-rework-result-failed",
    "scheduler-runtime.worker-rework-validation-passed",
    "scheduler-runtime.worker-rework-validation-failed",
    "scheduler-runtime.worker-rework-audit-approved",
    "scheduler-runtime.worker-rework-audit-blocked",
    "scheduler-runtime.worker-rework-audit-failed",
    "scheduler-runtime.integration-candidate-compiled",
    "scheduler-runtime.integration-check-handoff-completed",
    "scheduler-runtime.integration-outcome-recorded",
    "scheduler-runtime.controlled-step-recorded",
    "scheduler-runtime.run-completed",
    "scheduler-runtime.run-closeout-recorded",
  ]),
  timestamp: z.string(),
  status: z.enum(["initialized", "blocked"]).optional(),
  summary: z.string().optional(),
  artifactRefs: z.array(z.string()).optional(),
  payload: z.record(z.unknown()).optional(),
});

const controlledStepScopeValueSchema = z.union([z.string(), z.array(z.string())]);

const schedulerControlledStepForbiddenAuthoritySchema = z.object({
  loopAuthorized: z.literal(false),
  wholeWaveDispatchAuthorized: z.literal(false),
  slotAllocatorAuthorized: z.literal(false),
  fullParallelExecutorAuthorized: z.literal(false),
  sourceMutationAuthorized: z.literal(false),
  applyAuthorized: z.literal(false),
  closeAuthorized: z.literal(false),
  mergeAuthorized: z.literal(false),
  remoteLandingAuthorized: z.literal(false),
  harnessEvolutionAuthorized: z.literal(false),
});

const schedulerControlledStepPreStepEvidenceSchema = z.object({
  goalLoopDecisionId: z.string(),
  goalLoopIterationId: z.string(),
  goalLoopContinuationBriefId: z.string(),
  goalLoopNextStepPacketId: z.string(),
  goalLoopControllerPolicyId: z.string(),
  goalLoopGateReadinessPreflightId: z.string(),
});

const schedulerControlledStepPostStepEvidenceSchema = z.object({
  goalLoopDecisionId: z.string().optional(),
  goalLoopIterationId: z.string().optional(),
  goalLoopContinuationBriefId: z.string().optional(),
  goalLoopNextStepPacketId: z.string().optional(),
  recommendedActionType: z.string().optional(),
  continuationState: z.string().optional(),
  goalLoopControllerPolicyId: z.string().optional(),
  goalLoopGateReadinessPreflightId: z.string().optional(),
  currentGateActionType: z.string().optional(),
  evaluationWarning: z.string().optional(),
  readinessWarning: z.string().optional(),
  executionStarted: z.literal(false),
  concreteGateInvoked: z.literal(false),
  toolPolicyAuthorizedConcreteGate: z.literal(false),
});

const schedulerControlledStepNextCandidateSchema = z.object({
  actionType: z.string(),
  goalLoopNextStepPacketId: z.string().optional(),
  goalLoopControllerPolicyId: z.string().optional(),
  goalLoopGateReadinessPreflightId: z.string().optional(),
  readinessEvidencePrepared: z.boolean(),
  executionStarted: z.literal(false),
  authorizationGranted: z.literal(false),
  humanConfirmationStillRequired: z.literal(true),
});

const schedulerControlledStepHandoffSummarySchema = z.object({
  status: z.string(),
  stopReason: z.string(),
  executedActionType: z.string(),
  needsReevaluation: z.boolean(),
  warning: z.string().optional(),
  nextConfirmationCandidate: schedulerControlledStepNextCandidateSchema.optional(),
  executionStarted: z.literal(false),
  loopAuthorized: z.literal(false),
  wholeWaveDispatchAuthorized: z.literal(false),
  slotAllocatorAuthorized: z.literal(false),
});

const schedulerControlledLoopTurnRouteSummarySchema = z.object({
  version: z.literal("1.0"),
  authority: z.literal("scheduler-runtime-controlled-loop-turn-route-summary"),
  executedActionType: z.string(),
  resultKind: z.string().optional(),
  resultId: z.string().optional(),
  resultStatus: z.string().optional(),
  resultArtifact: z.string().optional(),
  routePosture: z.enum(["waiting", "recommending-gate", "awaiting-human-gate", "quality-routing", "integration-barrier", "terminal-handoff"]),
  postStepStatus: z.string(),
  nextCandidateActionType: z.string().optional(),
  humanGateRequired: z.boolean(),
  humanConfirmationStillRequired: z.literal(true),
  needsReevaluation: z.boolean(),
  warning: z.string().optional(),
  executionStarted: z.literal(false),
  loopAuthorized: z.literal(false),
  fullParallelExecutorAuthorized: z.literal(false),
  wholeWaveDispatchAuthorized: z.literal(false),
  slotAllocatorAuthorized: z.literal(false),
  sourceMutationAuthorized: z.literal(false),
  applyAuthorized: z.literal(false),
  closeAuthorized: z.literal(false),
  mergeAuthorized: z.literal(false),
  remoteLandingAuthorized: z.literal(false),
  harnessEvolutionAuthorized: z.literal(false),
});

export const schedulerControlledStepEvidenceSchema: z.ZodType<SchedulerControlledStepEvidence> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string().optional(),
  status: z.enum(["recorded", "recorded-with-warning"]),
  executedActionType: z.string(),
  targetScope: z.record(controlledStepScopeValueSchema),
  preStepEvidence: schedulerControlledStepPreStepEvidenceSchema,
  postStepEvidence: schedulerControlledStepPostStepEvidenceSchema,
  postStepHandoff: schedulerControlledStepHandoffSummarySchema,
  controlledStepResultSummary: z.record(z.union([z.string(), z.number(), z.boolean(), z.array(z.string()), z.null()])).optional(),
  controlledLoopTurnRouteSummary: schedulerControlledLoopTurnRouteSummarySchema.optional(),
  executionStarted: z.literal(true),
  stoppedAfterOneSchedulerTransition: z.literal(true),
  humanConfirmationStillRequired: z.literal(true),
  sourceMutated: z.literal(false),
  forbiddenAuthority: schedulerControlledStepForbiddenAuthoritySchema,
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerReconcileSnapshotSchema: z.ZodType<SchedulerReconcileSnapshot> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["generated", "blocked"]),
  schedulerRuntimeStateId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  claimIntents: z.array(claimIntentStateSchema),
  waves: z.array(waveStateSchema),
  plannedSlotDemand: z.number(),
  maxPlannedWaveWidth: z.number(),
  blockedCount: z.number(),
  warningCount: z.number(),
  warnings: z.array(z.string()),
  recoveryCheckpoint: z.string(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
});

const claimReservationIntentSchema = z.object({
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  status: z.enum(["reserved", "blocked"]),
  plannedSlotDemand: z.number(),
  sourceScopes: z.array(z.string()),
  blockedReasons: z.array(z.string()),
});

const sourceLockReservationSchema = z.object({
  scope: z.string(),
  waveIndex: z.number(),
  reservationIntentIds: z.array(z.string()),
  status: z.enum(["reserved", "blocked"]),
  blockedReasons: z.array(z.string()),
});

const waveReservationSchema = z.object({
  waveIndex: z.number(),
  reservationIntentIds: z.array(z.string()),
  reservedCount: z.number(),
  blockedCount: z.number(),
  plannedSlotDemand: z.number(),
  status: z.enum(["reserved", "blocked"]),
  blockedReasons: z.array(z.string()),
});

export const schedulerRuntimeClaimReservationSchema: z.ZodType<SchedulerRuntimeClaimReservation> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["reserved", "blocked", "rejected"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntents: z.array(claimReservationIntentSchema),
  waves: z.array(waveReservationSchema),
  sourceLocks: z.array(sourceLockReservationSchema),
  reservedCount: z.number(),
  blockedCount: z.number(),
  sourceLockCount: z.number(),
  supersedesReservationId: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
});

export const schedulerRuntimeWorkerStartSchema: z.ZodType<SchedulerRuntimeWorkerStart> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["started", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("coder"),
  taskId: z.string(),
  taskRunId: z.string(),
  workerLeaseId: z.string(),
  taskRunRoleId: z.string(),
  agentRoleId: z.string(),
  worktreeId: z.string().optional(),
  runId: z.string().optional(),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeWorkerResultSchema: z.ZodType<SchedulerRuntimeWorkerResult> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["evidence-ready", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerWorkerStartId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("coder"),
  taskId: z.string(),
  taskRunId: z.string(),
  workerLeaseId: z.string(),
  taskRunStatus: z.string(),
  workerLeaseStatus: z.string(),
  agentRoleId: z.string(),
  worktreeId: z.string().optional(),
  runId: z.string().optional(),
  runStatus: z.string().optional(),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeWorkerValidationSchema: z.ZodType<SchedulerRuntimeWorkerValidation> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["passed", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerWorkerStartId: z.string(),
  schedulerWorkerResultId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("validation"),
  taskId: z.string(),
  taskRunId: z.string(),
  workerLeaseId: z.string(),
  taskRunStatus: z.string(),
  worktreeId: z.string(),
  codeRunId: z.string(),
  validationRunId: z.string(),
  validationStatus: z.string(),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeWorkerAuditSchema: z.ZodType<SchedulerRuntimeWorkerAudit> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["approved", "approved-with-notes", "blocked", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerWorkerStartId: z.string(),
  schedulerWorkerResultId: z.string(),
  schedulerWorkerValidationId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("audit"),
  taskId: z.string(),
  taskRunId: z.string(),
  workerLeaseId: z.string(),
  taskRunStatus: z.string(),
  worktreeId: z.string(),
  codeRunId: z.string(),
  validationRunId: z.string(),
  validationStatus: z.string(),
  auditRunId: z.string(),
  auditStatus: z.enum(["approved", "approved-with-notes", "blocked", "failed"]),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeWorkerReworkPlanSchema: z.ZodType<SchedulerRuntimeWorkerReworkPlan> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.literal("planned"),
  blockingSource: z.enum(["validation-failed", "audit-blocked", "audit-failed"]),
  reworkReason: z.string(),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerWorkerStartId: z.string(),
  schedulerWorkerResultId: z.string(),
  schedulerWorkerValidationId: z.string(),
  schedulerWorkerAuditId: z.string().optional(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("bounded-rework"),
  taskId: z.string(),
  taskRunId: z.string(),
  workerLeaseId: z.string(),
  taskRunStatus: z.string(),
  targetWorktreeId: z.string(),
  targetCodeRunId: z.string(),
  validationRunId: z.string(),
  validationStatus: z.string(),
  auditRunId: z.string().optional(),
  auditStatus: z.enum(["approved", "approved-with-notes", "blocked", "failed"]).optional(),
  futureCodeGateMode: z.literal("scheduler-claim-rework"),
  recoveryKeyInputs: z.array(z.string()),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeWorkerReworkStartSchema: z.ZodType<SchedulerRuntimeWorkerReworkStart> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["started", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerWorkerStartId: z.string(),
  schedulerWorkerResultId: z.string(),
  schedulerWorkerValidationId: z.string(),
  schedulerWorkerAuditId: z.string().optional(),
  schedulerWorkerReworkPlanId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("bounded-rework"),
  taskId: z.string(),
  originalTaskRunId: z.string(),
  originalWorkerLeaseId: z.string(),
  reworkTaskRunId: z.string(),
  reworkWorkerLeaseId: z.string(),
  taskRunRoleId: z.string(),
  agentRoleId: z.string(),
  worktreeId: z.string(),
  originalCodeRunId: z.string(),
  reworkRunId: z.string().optional(),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeWorkerReworkResultSchema: z.ZodType<SchedulerRuntimeWorkerReworkResult> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["evidence-ready", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerWorkerStartId: z.string(),
  schedulerWorkerResultId: z.string(),
  schedulerWorkerValidationId: z.string(),
  schedulerWorkerAuditId: z.string().optional(),
  schedulerWorkerReworkPlanId: z.string(),
  schedulerWorkerReworkStartId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("bounded-rework"),
  taskId: z.string(),
  originalTaskRunId: z.string(),
  originalWorkerLeaseId: z.string(),
  originalCodeRunId: z.string(),
  reworkTaskRunId: z.string(),
  reworkWorkerLeaseId: z.string(),
  taskRunStatus: z.string(),
  workerLeaseStatus: z.string(),
  agentRoleId: z.string(),
  worktreeId: z.string(),
  reworkRunId: z.string().optional(),
  reworkRunStatus: z.string().optional(),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeWorkerReworkValidationSchema: z.ZodType<SchedulerRuntimeWorkerReworkValidation> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["passed", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerWorkerStartId: z.string(),
  schedulerWorkerResultId: z.string(),
  schedulerWorkerValidationId: z.string(),
  schedulerWorkerAuditId: z.string().optional(),
  schedulerWorkerReworkPlanId: z.string(),
  schedulerWorkerReworkStartId: z.string(),
  schedulerWorkerReworkResultId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("validation"),
  taskId: z.string(),
  originalTaskRunId: z.string(),
  originalWorkerLeaseId: z.string(),
  originalCodeRunId: z.string(),
  reworkTaskRunId: z.string(),
  reworkWorkerLeaseId: z.string(),
  taskRunStatus: z.string(),
  worktreeId: z.string(),
  reworkRunId: z.string(),
  validationRunId: z.string(),
  validationStatus: z.enum(["passed", "failed"]),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRuntimeWorkerReworkAuditSchema: z.ZodType<SchedulerRuntimeWorkerReworkAudit> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["approved", "approved-with-notes", "blocked", "failed"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerWorkerStartId: z.string(),
  schedulerWorkerResultId: z.string(),
  schedulerWorkerValidationId: z.string(),
  schedulerWorkerAuditId: z.string().optional(),
  schedulerWorkerReworkPlanId: z.string(),
  schedulerWorkerReworkStartId: z.string(),
  schedulerWorkerReworkResultId: z.string(),
  schedulerWorkerReworkValidationId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  reservationIntentId: z.string(),
  claimIntentId: z.string(),
  plannedWorkerKey: z.string(),
  nodeId: z.string(),
  unitId: z.string(),
  waveIndex: z.number(),
  stageId: z.string(),
  stage: z.literal("audit"),
  taskId: z.string(),
  originalTaskRunId: z.string(),
  originalWorkerLeaseId: z.string(),
  originalCodeRunId: z.string(),
  reworkTaskRunId: z.string(),
  reworkWorkerLeaseId: z.string(),
  taskRunStatus: z.string(),
  worktreeId: z.string(),
  reworkRunId: z.string(),
  validationRunId: z.string(),
  validationStatus: z.enum(["passed", "failed"]),
  auditRunId: z.string(),
  auditStatus: z.enum(["approved", "approved-with-notes", "blocked", "failed"]),
  failureReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const schedulerIntegrationCandidateReadyTargetSchema = z.object({
  worktreeId: z.string(),
  worktreeDiffHash: z.string(),
  diffStat: z.string(),
  sourceHead: z.string().nullable(),
  validationRunId: z.string(),
  auditRunId: z.string(),
});

const schedulerIntegrationCandidateOutputSchema = z.object({
  outputId: z.string(),
  kind: z.enum(["worker", "rework", "inconsistency"]),
  status: z.enum(["ready", "blocked"]),
  blockingReasons: z.array(z.string()),
  readinessKind: z.string().optional(),
  readinessMessage: z.string().optional(),
  schedulerWorkerAuditId: z.string().optional(),
  schedulerWorkerReworkAuditId: z.string().optional(),
  schedulerWorkerStartId: z.string().optional(),
  schedulerWorkerResultId: z.string().optional(),
  schedulerWorkerValidationId: z.string().optional(),
  schedulerWorkerReworkPlanId: z.string().optional(),
  schedulerWorkerReworkStartId: z.string().optional(),
  schedulerWorkerReworkResultId: z.string().optional(),
  schedulerWorkerReworkValidationId: z.string().optional(),
  reservationIntentId: z.string().optional(),
  claimIntentId: z.string().optional(),
  plannedWorkerKey: z.string().optional(),
  nodeId: z.string().optional(),
  unitId: z.string().optional(),
  waveIndex: z.number().optional(),
  taskId: z.string().optional(),
  taskRunId: z.string().optional(),
  workerLeaseId: z.string().optional(),
  worktreeId: z.string().optional(),
  codeRunId: z.string().optional(),
  validationRunId: z.string().optional(),
  auditRunId: z.string().optional(),
  worktreeDiffHash: z.string().optional(),
  diffStat: z.string().optional(),
  sourceHead: z.string().nullable().optional(),
  artifactRefs: z.array(z.string()),
});

export const schedulerIntegrationCandidateSchema: z.ZodType<SchedulerIntegrationCandidate> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["ready", "waiting", "blocked"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  outputs: z.array(schedulerIntegrationCandidateOutputSchema),
  readyTargets: z.array(schedulerIntegrationCandidateReadyTargetSchema),
  readyWorktreeIds: z.array(z.string()),
  readyCount: z.number(),
  blockedCount: z.number(),
  waitingReason: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const schedulerIntegrationCheckHandoffTargetSchema = z.object({
  worktreeId: z.string(),
  worktreeDiffHash: z.string(),
  diffStat: z.string(),
  sourceHead: z.string().nullable(),
  validationRunId: z.string(),
  auditRunId: z.string(),
});

export const schedulerIntegrationCheckHandoffSchema: z.ZodType<SchedulerIntegrationCheckHandoff> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.literal("completed"),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerIntegrationCandidateId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  readyTargets: z.array(schedulerIntegrationCheckHandoffTargetSchema),
  readyWorktreeIds: z.array(z.string()),
  integrationCheckId: z.string(),
  integrationCheckStatus: z.string(),
  resultTargetWorktreeIds: z.array(z.string()),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const schedulerIntegrationOutcomeTargetSchema = z.object({
  worktreeId: z.string(),
  changeId: z.string(),
  diffHash: z.string(),
  sourceHead: z.string().nullable(),
  applied: z.boolean(),
  appliedAt: z.string().optional(),
  appliedCommit: z.string().optional(),
});

export const schedulerIntegrationOutcomeSchema: z.ZodType<SchedulerIntegrationOutcome> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["applied", "discarded", "blocked"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerIntegrationCandidateId: z.string(),
  schedulerIntegrationCheckHandoffId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  integrationCheckId: z.string(),
  integrationCheckStatus: z.string(),
  outcomeReason: z.string(),
  readyWorktreeIds: z.array(z.string()),
  resultTargetWorktreeIds: z.array(z.string()),
  targets: z.array(schedulerIntegrationOutcomeTargetSchema),
  appliedAt: z.string().optional(),
  sourceHead: z.string().nullable(),
  latestArtifactHash: z.string().optional(),
  latestArtifactRef: z.string().optional(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRunCompletionSchema: z.ZodType<SchedulerRunCompletion> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["completed-applied", "completed-discarded", "completed-blocked"]),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerIntegrationCandidateId: z.string(),
  schedulerIntegrationCheckHandoffId: z.string(),
  schedulerIntegrationOutcomeId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  integrationCheckId: z.string(),
  integrationCheckStatus: z.string(),
  outcomeStatus: z.enum(["applied", "discarded", "blocked"]),
  outcomeReason: z.string(),
  readyWorktreeIds: z.array(z.string()),
  resultTargetWorktreeIds: z.array(z.string()),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRunBlockedCloseoutSchema: z.ZodType<SchedulerRunBlockedCloseout> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  schedulerRunId: z.string(),
  schedulerMode: z.literal("parallel-readiness-v1"),
  status: z.enum(["blocked", "exhausted", "stopped"]),
  reason: z.enum(["candidate-waiting-exhausted", "candidate-blocked", "candidate-inconsistent", "user-stopped"]),
  closeoutReason: z.string(),
  schedulerRuntimeStateId: z.string(),
  schedulerReconcileSnapshotId: z.string(),
  schedulerClaimReservationId: z.string(),
  schedulerIntegrationCandidateId: z.string(),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  readyWorktreeIds: z.array(z.string()),
  readyCount: z.number(),
  blockedCount: z.number(),
  blockedReasons: z.array(z.string()),
  unstartedReservedIntentIds: z.array(z.string()),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
