import { z } from "zod";
import type { IntegrationCheckRecord } from "./types.js";

export const integrationCheckSchema = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  projectId: z.string().nullable(),
  status: z.enum(["passed", "conflict", "validation-failed", "audit-failed", "stale-result", "failed", "applied", "discarded"]),
  resultTargets: z.array(z.object({
    changeId: z.string(),
    worktreeId: z.string(),
    diffHash: z.string(),
    diffStat: z.string(),
    sourceHead: z.string().nullable(),
  })),
  sourceHead: z.string().nullable(),
  createdAt: z.string(),
  finishedAt: z.string().optional(),
  appliedAt: z.string().optional(),
  summary: z.string(),
  riskSummary: z.string(),
  artifactRefs: z.array(z.string()),
  artifacts: z.array(z.object({
    kind: z.enum(["combined", "repaired"]),
    path: z.string(),
    hash: z.string(),
    createdAt: z.string(),
    source: z.enum(["integration-check", "integration-fix-agent"]),
  })).optional(),
  latestArtifactHash: z.string().optional(),
  latestArtifactRef: z.string().optional(),
  aggregateValidation: z.object({
    id: z.string(),
    status: z.enum(["passed", "failed"]),
    command: z.array(z.string()),
    exitCode: z.number().nullable(),
    stdout: z.string(),
    stderr: z.string(),
    artifactRef: z.string(),
    createdAt: z.string(),
  }).optional(),
  aggregateAudit: z.object({
    id: z.string(),
    status: z.enum(["approved", "blocked", "failed"]),
    summary: z.string(),
    findings: z.array(z.string()),
    artifactRef: z.string(),
    createdAt: z.string(),
  }).optional(),
  fixAttempts: z.array(z.object({
    id: z.string(),
    roleId: z.literal("integration-fix-agent"),
    status: z.enum(["completed", "failed"]),
    reason: z.string(),
    inputArtifactRef: z.string(),
    outputArtifactRef: z.string().optional(),
    outputArtifactHash: z.string().optional(),
    summary: z.string(),
    startedAt: z.string(),
    finishedAt: z.string(),
  })).optional(),
  integrationWorktreePath: z.string().optional(),
  blockingIssues: z.array(z.string()),
  warnings: z.array(z.string()),
}).transform((value) => ({
  ...value,
  artifacts: value.artifacts ?? [],
  fixAttempts: value.fixAttempts ?? [],
})) as unknown as z.ZodType<IntegrationCheckRecord>;
