import { z } from "zod";
import type { RemoteLandingStateSnapshot, RemoteLandingReadiness, RemoteLandingAttempt, RemoteLandingResult } from "../types/index.js";

export const stateSnapshotSchema: z.ZodType<RemoteLandingStateSnapshot> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  prDraftPackageId: z.string(),
  landingPackageId: z.string(),
  projectId: z.string().nullable(),
  prUrl: z.string().optional(),
  state: z.string(),
  isDraft: z.boolean(),
  reviewDecision: z.string().nullable().optional(),
  feedbackClassification: z.enum(["no-action", "checks-failed", "changes-requested", "inline-comments-actionable", "comments-only", "user-pushback-requested", "provider-unavailable", "stale-pr"]).optional(),
  failedChecksCount: z.number(),
  commentsCount: z.number(),
  mergeable: z.string().nullable().optional(),
  mergeStateStatus: z.string().nullable().optional(),
  headRefName: z.string().nullable().optional(),
  baseRefName: z.string().nullable().optional(),
  headRefOid: z.string().nullable().optional(),
  baseRefOid: z.string().nullable().optional(),
  evidenceRefs: z.array(z.string()),
  createdAt: z.string(),
});

export const readinessSchema: z.ZodType<RemoteLandingReadiness> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  prDraftPackageId: z.string(),
  landingPackageId: z.string(),
  projectId: z.string().nullable(),
  status: z.enum(["ready", "ready-with-comments", "missing-pr", "provider-unavailable", "draft", "closed", "already-merged", "checks-failed", "actionable-feedback", "stale-pr", "merge-unavailable"]),
  canMerge: z.boolean(),
  mergeMethod: z.literal("squash"),
  summary: z.string(),
  reason: z.string(),
  confirmEffect: z.string(),
  riskSummary: z.string(),
  prUrl: z.string().optional(),
  stateSnapshotArtifact: z.string(),
  readinessArtifact: z.string(),
  summaryArtifact: z.string(),
  evidenceRefs: z.array(z.string()),
  createdAt: z.string(),
});

export const attemptSchema: z.ZodType<RemoteLandingAttempt> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  readinessId: z.string(),
  prDraftPackageId: z.string(),
  landingPackageId: z.string(),
  projectId: z.string().nullable(),
  prUrl: z.string().optional(),
  mergeMethod: z.literal("squash"),
  status: z.enum(["started", "merged", "failed"]),
  artifactRefs: z.array(z.string()),
  startedAt: z.string(),
  finishedAt: z.string().optional(),
});

export const resultSchema: z.ZodType<RemoteLandingResult> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  attemptId: z.string(),
  readinessId: z.string(),
  prDraftPackageId: z.string(),
  landingPackageId: z.string(),
  projectId: z.string().nullable(),
  prUrl: z.string().optional(),
  status: z.enum(["merged", "failed"]),
  mergeMethod: z.literal("squash"),
  mergeCommit: z.string().nullable().optional(),
  mergedAt: z.string().nullable().optional(),
  failureReason: z.string().optional(),
  artifactRefs: z.array(z.string()),
  createdAt: z.string(),
});
