import { z } from "zod";
import type { WorkflowGraphPlan } from "../types/index.js";
import type { DecompositionPlan, DecompositionReadinessManifest, TaskQueueProposal } from "./types.js";

const recoveryKeyInputsSchema = z.object({
  changeId: z.string(),
  planningBundleId: z.string().optional(),
  acceptedArtifactRefs: z.array(z.string()),
  contextScope: z.literal("selected-demand"),
  sourceRevision: z.string().optional(),
  worktreeBase: z.string().optional(),
  rolePolicyProfile: z.string(),
  notes: z.array(z.string()),
});

const scopeExpansionSchema = z.object({
  scope: z.string(),
  reason: z.string(),
  accepted: z.boolean(),
});

export const decompositionPlanSchema: z.ZodType<DecompositionPlan> = z.object({
  id: z.string(),
  changeId: z.string(),
  status: z.enum(["draft", "confirmed", "superseded", "rejected"]),
  recommendation: z.enum(["single-change", "taskgraph-sequential", "taskgraph-parallel-candidate", "multi-change-candidate", "needs-clarification"]),
  rationale: z.string(),
  units: z.array(z.object({
    id: z.string(),
    title: z.string(),
    summary: z.string(),
    taskIds: z.array(z.string()),
    acIds: z.array(z.string()),
    scopeHints: z.array(z.string()),
    dependsOn: z.array(z.string()),
    recommendedRoleId: z.string(),
  })),
  dependencies: z.array(z.object({
    from: z.string(),
    to: z.string(),
    kind: z.enum(["blocks", "synthesizes", "conflicts"]),
  })),
  conflictScopes: z.array(z.string()),
  sourceScopeConstraints: z.array(z.string()).optional(),
  scopeExpansions: z.array(scopeExpansionSchema).optional(),
  riskSummary: z.string(),
  openQuestions: z.array(z.string()),
  artifactRefs: z.array(z.string()),
  recoveryKeyInputs: recoveryKeyInputsSchema,
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const decompositionReadinessManifestSchema = z.object({
  id: z.string(),
  changeId: z.string(),
  decompositionPlanId: z.string(),
  status: z.enum(["ready-for-single-change", "ready-for-sequential-taskqueue-proposal", "ready-for-scheduler-contract", "blocked-parallel-guardrails", "blocked-multi-change-boundary", "blocked-needs-clarification", "invalid"]),
  recommendation: z.enum(["single-change", "taskgraph-sequential", "taskgraph-parallel-candidate", "multi-change-candidate", "needs-clarification"]),
  executable: z.literal(false),
  schedulerEligible: z.boolean(),
  nextAllowedAction: z.enum(["code.run", "taskqueue.proposal", "scheduler.contract", "clarification.answer", "none"]),
  units: z.array(z.object({
    id: z.string(),
    title: z.string(),
    taskIds: z.array(z.string()),
    acIds: z.array(z.string()),
    dependsOn: z.array(z.string()),
    guardrailStatus: z.enum(["passed", "blocked", "failed"]),
    sourceScopes: z.array(z.string()),
  })),
  dependencies: z.array(z.object({
    from: z.string(),
    to: z.string(),
    kind: z.enum(["blocks", "synthesizes", "conflicts"]),
  })),
  conflictScopes: z.array(z.string()),
  guardrails: z.array(z.object({
    id: z.string(),
    status: z.enum(["passed", "blocked", "failed"]),
    summary: z.string(),
    refs: z.array(z.string()),
  })),
  recoveryKeyMaterial: recoveryKeyInputsSchema.extend({
    decompositionPlanId: z.string(),
    taskIds: z.array(z.string()),
    acIds: z.array(z.string()),
  }),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
}) as z.ZodType<DecompositionReadinessManifest>;

export const taskQueueProposalSchema = z.object({
  id: z.string(),
  changeId: z.string(),
  decompositionPlanId: z.string(),
  readinessManifestId: z.string(),
  status: z.enum(["draft", "confirmed", "started", "superseded", "rejected"]),
  recommendation: z.literal("taskgraph-sequential"),
  queueMode: z.literal("sequential"),
  items: z.array(z.object({
    id: z.string(),
    taskId: z.string(),
    unitId: z.string(),
    title: z.string(),
    order: z.number(),
    dependsOn: z.array(z.string()),
    sourceScopes: z.array(z.string()),
    acIds: z.array(z.string()),
  })),
  dependencies: z.array(z.object({
    from: z.string(),
    to: z.string(),
    kind: z.enum(["blocks", "synthesizes", "conflicts"]),
  })),
  conflictScopes: z.array(z.string()),
  sourceArtifactHashes: z.record(z.string()),
  recoveryKeyMaterial: recoveryKeyInputsSchema.extend({
    decompositionPlanId: z.string(),
    taskIds: z.array(z.string()),
    acIds: z.array(z.string()),
  }),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
}) as z.ZodType<TaskQueueProposal>;

export const workflowGraphPlanSchema: z.ZodType<WorkflowGraphPlan> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  status: z.enum(["compiled", "superseded", "rejected"]),
  graphMode: z.literal("sequential-v1"),
  decompositionPlanId: z.string(),
  readinessManifestId: z.string(),
  taskQueueProposalId: z.string(),
  nodes: z.array(z.object({
    id: z.string(),
    taskId: z.string(),
    taskQueueProposalItemId: z.string(),
    unitId: z.string(),
    title: z.string(),
    order: z.number(),
    stages: z.array(z.enum(["coder", "validation", "audit", "bounded-rework"])),
    acIds: z.array(z.string()),
    sourceScopes: z.array(z.string()),
  })),
  edges: z.array(z.object({
    from: z.string(),
    to: z.string(),
    kind: z.enum(["task-order", "stage-order"]),
  })),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
