import type { GoalLoopContinuationBrief, GoalLoopDecision, GoalLoopIteration, GoalLoopNextStepPacket } from "./types.js";

export function renderGoalLoopDecisionMarkdown(decision: GoalLoopDecision): string {
  const lines = [
    `# GoalLoopDecision ${decision.id}`,
    "",
    `- Change: ${decision.changeId}`,
    `- Authority: ${decision.authority}`,
    `- Decision: ${decision.decisionKind}`,
    `- Human gate required: ${decision.humanGateRequired ? "yes" : "no"}`,
    `- Execution started: ${decision.executionStarted ? "yes" : "no"}`,
    "",
    "## Summary",
    "",
    decision.summary,
    "",
    "## Recommended Action",
    "",
    decision.recommendedAction
      ? `- ${decision.recommendedAction.actionType}: ${decision.recommendedAction.reason}`
      : "- None.",
    ...(decision.recommendedAction
      ? ["", "### Scope", "", ...Object.entries(decision.recommendedAction.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`)]
      : []),
    "",
    "## Conflict Assessment",
    "",
    `- Level: ${decision.conflictAssessment.level}`,
    `- Parallel eligible: ${decision.conflictAssessment.parallelEligible ? "yes" : "no"}`,
    ...decision.conflictAssessment.reasons.map((reason) => `- ${reason}`),
    "",
    "## Completion Audit",
    "",
    `- Status: ${decision.completionAudit.status}`,
    "",
    "### Evidence",
    "",
    ...(decision.completionAudit.evidence.length ? decision.completionAudit.evidence.map((item) => `- ${item}`) : ["- None."]),
    "",
    "### Missing",
    "",
    ...(decision.completionAudit.missing.length ? decision.completionAudit.missing.map((item) => `- ${item}`) : ["- None."]),
    "",
    "## Source Evidence",
    "",
    ...(decision.sourceEvidenceRefs.length
      ? decision.sourceEvidenceRefs.map((ref) => `- ${ref.kind}${ref.id ? ` ${ref.id}` : ""}${ref.status ? ` (${ref.status})` : ""}: ${ref.summary}`)
      : ["- None."]),
    "",
    "## Forbidden Actions",
    "",
    ...(decision.forbiddenActions.length
      ? decision.forbiddenActions.map((action) => `- ${action.actionType}: ${action.reason}`)
      : ["- None."]),
    "",
  ];
  return `${lines.join("\n")}\n`;
}

export function renderGoalLoopIterationMarkdown(iteration: GoalLoopIteration): string {
  const lines = [
    `# GoalLoopIteration ${iteration.id}`,
    "",
    `- Change: ${iteration.changeId}`,
    `- Ordinal: ${iteration.ordinal}`,
    `- Authority: ${iteration.authority}`,
    `- Trigger: ${iteration.trigger}`,
    `- Iteration status: ${iteration.iterationStatus}`,
    `- Continuation verdict: ${iteration.continuationVerdict}`,
    `- Continuation state: ${iteration.continuationState}`,
    `- GoalLoopDecision: ${iteration.goalLoopDecisionId}`,
    `- Previous iteration: ${iteration.previousGoalLoopIterationId ?? "none"}`,
    `- Previous decision: ${iteration.previousGoalLoopDecisionId ?? "none"}`,
    `- Human gate required: ${iteration.humanGateRequired ? "yes" : "no"}`,
    `- Execution started: ${iteration.executionStarted ? "yes" : "no"}`,
    "",
    "## Summary",
    "",
    iteration.summary,
    "",
    "## Recommended Action Snapshot",
    "",
    iteration.recommendedAction
      ? `- ${iteration.recommendedAction.actionType}: ${iteration.recommendedAction.reason}`
      : "- None.",
    ...(iteration.recommendedAction
      ? ["", "### Scope", "", ...Object.entries(iteration.recommendedAction.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`)]
      : []),
    "",
    "## Continuation Control Policy",
    "",
    `- Authority: ${iteration.controlPolicy.authority}`,
    `- Can auto-continue: ${iteration.controlPolicy.canAutoContinue ? "yes" : "no"}`,
    `- Can auto-execute recommended action: ${iteration.controlPolicy.canAutoExecuteRecommendedAction ? "yes" : "no"}`,
    `- Requires human gate: ${iteration.controlPolicy.requiresHumanGate ? "yes" : "no"}`,
    `- Recommended action type: ${iteration.controlPolicy.recommendedActionType ?? "none"}`,
    `- Reason: ${iteration.controlPolicy.reason}`,
    "",
    "## Budget / Accounting Signal",
    "",
    `- Status: ${iteration.budgetSignal.status}`,
    `- Summary: ${iteration.budgetSignal.summary}`,
    ...(iteration.budgetSignal.tokenBudget !== undefined ? [`- Token budget: ${iteration.budgetSignal.tokenBudget}`] : []),
    ...(iteration.budgetSignal.tokensUsed !== undefined ? [`- Tokens used: ${iteration.budgetSignal.tokensUsed}`] : []),
    ...(iteration.budgetSignal.remainingTokens !== undefined ? [`- Remaining tokens: ${iteration.budgetSignal.remainingTokens}`] : []),
    "",
    "## Resume Preconditions",
    "",
    ...(iteration.resumePreconditions.length
      ? iteration.resumePreconditions.map((item) => `- ${item.kind}${item.id ? ` ${item.id}` : ""}: ${item.satisfied ? "satisfied" : "pending"} - ${item.summary}`)
      : ["- None."]),
    "",
    "## Suppression Reason",
    "",
    iteration.suppressedBecause
      ? `- ${iteration.suppressedBecause.reason}: ${iteration.suppressedBecause.summary}`
      : "- None.",
    "",
    "## Conflict Assessment",
    "",
    `- Level: ${iteration.conflictAssessment.level}`,
    `- Parallel eligible: ${iteration.conflictAssessment.parallelEligible ? "yes" : "no"}`,
    ...iteration.conflictAssessment.reasons.map((reason) => `- ${reason}`),
    "",
    "## Completion Audit",
    "",
    `- Status: ${iteration.completionAudit.status}`,
    "",
    "### Evidence",
    "",
    ...(iteration.completionAudit.evidence.length ? iteration.completionAudit.evidence.map((item) => `- ${item}`) : ["- None."]),
    "",
    "### Missing",
    "",
    ...(iteration.completionAudit.missing.length ? iteration.completionAudit.missing.map((item) => `- ${item}`) : ["- None."]),
    "",
    "## Source Evidence",
    "",
    ...(iteration.sourceEvidenceRefs.length
      ? iteration.sourceEvidenceRefs.map((ref) => `- ${ref.kind}${ref.id ? ` ${ref.id}` : ""}${ref.status ? ` (${ref.status})` : ""}: ${ref.summary}`)
      : ["- None."]),
    "",
    "## Boundary",
    "",
    "- This iteration is continuation evidence only.",
    "- It does not execute the recommended action.",
    "- Concrete next steps still require their own scoped Harness confirmation.",
    "",
  ];
  return `${lines.join("\n")}\n`;
}

export function renderGoalLoopContinuationBriefMarkdown(brief: GoalLoopContinuationBrief): string {
  const lines = [
    `# GoalLoopContinuationBrief ${brief.id}`,
    "",
    `- Change: ${brief.changeId}`,
    `- Authority: ${brief.authority}`,
    `- Source GoalLoopDecision: ${brief.sourceGoalLoopDecisionId}`,
    `- Source GoalLoopIteration: ${brief.sourceGoalLoopIterationId}`,
    `- Iteration ordinal: ${brief.iterationOrdinal}`,
    `- Decision: ${brief.decisionKind}`,
    `- Continuation verdict: ${brief.continuationVerdict}`,
    `- Continuation state: ${brief.continuationState}`,
    `- Human gate required: ${brief.humanGateRequired ? "yes" : "no"}`,
    `- Execution started: ${brief.executionStarted ? "yes" : "no"}`,
    "",
    "## Summary",
    "",
    brief.summary,
    "",
    "## Main Agent Instructions",
    "",
    ...brief.mainAgentInstructions.map((instruction) => `- ${instruction}`),
    "",
    "## Staleness / Re-read Instruction",
    "",
    brief.stalenessInstruction,
    "",
    "## Recommended Action Snapshot",
    "",
    brief.recommendedAction
      ? `- ${brief.recommendedAction.actionType}: ${brief.recommendedAction.reason}`
      : "- None.",
    ...(brief.recommendedAction
      ? ["", "### Scope", "", ...Object.entries(brief.recommendedAction.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`)]
      : []),
    "",
    "## Continuation Control Policy",
    "",
    `- Authority: ${brief.controlPolicy.authority}`,
    `- Can auto-continue: ${brief.controlPolicy.canAutoContinue ? "yes" : "no"}`,
    `- Can auto-execute recommended action: ${brief.controlPolicy.canAutoExecuteRecommendedAction ? "yes" : "no"}`,
    `- Requires human gate: ${brief.controlPolicy.requiresHumanGate ? "yes" : "no"}`,
    `- Recommended action type: ${brief.controlPolicy.recommendedActionType ?? "none"}`,
    `- Reason: ${brief.controlPolicy.reason}`,
    "",
    "## Budget / Accounting Signal",
    "",
    `- Status: ${brief.budgetSignal.status}`,
    `- Summary: ${brief.budgetSignal.summary}`,
    ...(brief.budgetSignal.tokenBudget !== undefined ? [`- Token budget: ${brief.budgetSignal.tokenBudget}`] : []),
    ...(brief.budgetSignal.tokensUsed !== undefined ? [`- Tokens used: ${brief.budgetSignal.tokensUsed}`] : []),
    ...(brief.budgetSignal.remainingTokens !== undefined ? [`- Remaining tokens: ${brief.budgetSignal.remainingTokens}`] : []),
    "",
    "## Resume Preconditions",
    "",
    ...(brief.resumePreconditions.length
      ? brief.resumePreconditions.map((item) => `- ${item.kind}${item.id ? ` ${item.id}` : ""}: ${item.satisfied ? "satisfied" : "pending"} - ${item.summary}`)
      : ["- None."]),
    "",
    "## Suppression Reason",
    "",
    brief.suppressedBecause
      ? `- ${brief.suppressedBecause.reason}: ${brief.suppressedBecause.summary}`
      : "- None.",
    "",
    "## Conflict Assessment",
    "",
    `- Level: ${brief.conflictAssessment.level}`,
    `- Parallel eligible: ${brief.conflictAssessment.parallelEligible ? "yes" : "no"}`,
    ...brief.conflictAssessment.reasons.map((reason) => `- ${reason}`),
    "",
    "## Completion Audit",
    "",
    `- Status: ${brief.completionAudit.status}`,
    "",
    "### Evidence",
    "",
    ...(brief.completionAudit.evidence.length ? brief.completionAudit.evidence.map((item) => `- ${item}`) : ["- None."]),
    "",
    "### Missing",
    "",
    ...(brief.completionAudit.missing.length ? brief.completionAudit.missing.map((item) => `- ${item}`) : ["- None."]),
    "",
    "## Source Evidence",
    "",
    ...(brief.sourceEvidenceRefs.length
      ? brief.sourceEvidenceRefs.map((ref) => `- ${ref.kind}${ref.id ? ` ${ref.id}` : ""}${ref.status ? ` (${ref.status})` : ""}: ${ref.summary}`)
      : ["- None."]),
    "",
    "## Forbidden Execution Statements",
    "",
    ...brief.forbiddenExecutionStatements.map((statement) => `- ${statement}`),
    "",
    "## Forbidden Actions",
    "",
    ...(brief.forbiddenActions.length
      ? brief.forbiddenActions.map((action) => `- ${action.actionType}: ${action.reason}`)
      : ["- None."]),
    "",
    "## Boundary",
    "",
    "- This brief is continuation handoff evidence only.",
    "- It is not a hidden next turn, scheduler loop, workflow truth, or execution authorization.",
    "- The next main Agent turn must re-read current Change evidence before relying on this brief.",
    "",
  ];
  return `${lines.join("\n")}\n`;
}

export function renderGoalLoopNextStepPacketMarkdown(packet: GoalLoopNextStepPacket): string {
  const lines = [
    `# GoalLoopNextStepPacket ${packet.id}`,
    "",
    `- Change: ${packet.changeId}`,
    `- Authority: ${packet.authority}`,
    `- Source GoalLoopDecision: ${packet.sourceGoalLoopDecisionId}`,
    `- Source GoalLoopIteration: ${packet.sourceGoalLoopIterationId}`,
    `- Source GoalLoopContinuationBrief: ${packet.sourceGoalLoopContinuationBriefId}`,
    `- Iteration ordinal: ${packet.iterationOrdinal}`,
    `- Decision: ${packet.decisionKind}`,
    `- Continuation verdict: ${packet.continuationVerdict}`,
    `- Continuation state: ${packet.continuationState}`,
    `- Recommendation state: ${packet.recommendationState}`,
    `- Separate gate required: ${packet.separateGateRequired ? "yes" : "no"}`,
    `- Human gate required: ${packet.humanGateRequired ? "yes" : "no"}`,
    `- Execution started: ${packet.executionStarted ? "yes" : "no"}`,
    "",
    "## Summary",
    "",
    packet.summary,
    "",
    "## Recommended Action Snapshot",
    "",
    packet.recommendedAction
      ? `- ${packet.recommendedAction.actionType}: ${packet.recommendedAction.reason}`
      : "- None.",
    ...(packet.recommendedAction
      ? ["", "### Scope", "", ...Object.entries(packet.recommendedAction.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`)]
      : []),
    "",
    "## Revalidation Checklist",
    "",
    ...packet.revalidationChecklist.map((item) => `- ${item}`),
    "",
    "## Main Agent Instructions",
    "",
    ...packet.mainAgentInstructions.map((item) => `- ${item}`),
    "",
    "## Staleness Instruction",
    "",
    packet.stalenessInstruction,
    "",
    "## Conflict Assessment",
    "",
    `- Level: ${packet.conflictAssessment.level}`,
    `- Parallel eligible: ${packet.conflictAssessment.parallelEligible ? "yes" : "no"}`,
    ...packet.conflictAssessment.reasons.map((reason) => `- ${reason}`),
    "",
    "## Completion Audit",
    "",
    `- Status: ${packet.completionAudit.status}`,
    "",
    "### Evidence",
    "",
    ...(packet.completionAudit.evidence.length ? packet.completionAudit.evidence.map((item) => `- ${item}`) : ["- None."]),
    "",
    "### Missing",
    "",
    ...(packet.completionAudit.missing.length ? packet.completionAudit.missing.map((item) => `- ${item}`) : ["- None."]),
    "",
    "## Source Evidence",
    "",
    ...(packet.sourceEvidenceRefs.length
      ? packet.sourceEvidenceRefs.map((ref) => `- ${ref.kind}${ref.id ? ` ${ref.id}` : ""}${ref.status ? ` (${ref.status})` : ""}: ${ref.summary}`)
      : ["- None."]),
    "",
    "## Forbidden Execution Statements",
    "",
    ...packet.forbiddenExecutionStatements.map((statement) => `- ${statement}`),
    "",
    "## Boundary",
    "",
    "- This packet is main-Agent resume context only.",
    "- It is not a hidden continuation turn, workflow truth, scheduler loop, or execution authorization.",
    "- Any recommended action must be revalidated and confirmed through its own scoped Harness gate.",
    "",
  ];
  return `${lines.join("\n")}\n`;
}
