import type { GoalLoopContinuationBrief, GoalLoopControllerPolicy, GoalLoopDecision, GoalLoopFeedback, GoalLoopGateReadinessPreflight, GoalLoopIteration, GoalLoopNextStepPacket } from "./types.js";

export function renderGoalLoopDecisionMarkdown(decision: GoalLoopDecision): string {
  const lines = [
    `# GoalLoopDecision ${decision.id}`,
    "",
    `- Change: ${decision.changeId}`,
    `- Authority: ${decision.authority}`,
    `- Decision: ${decision.decisionKind}`,
    `- Human gate required: ${decision.humanGateRequired ? "yes" : "no"}`,
    `- Execution started: ${decision.executionStarted ? "yes" : "no"}`,
    "",
    "## Summary",
    "",
    decision.summary,
    "",
    "## Recommended Action",
    "",
    decision.recommendedAction
      ? `- ${decision.recommendedAction.actionType}: ${decision.recommendedAction.reason}`
      : "- None.",
    ...(decision.recommendedAction
      ? ["", "### Scope", "", ...Object.entries(decision.recommendedAction.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`)]
      : []),
    "",
    "## Conflict Assessment",
    "",
    `- Level: ${decision.conflictAssessment.level}`,
    `- Parallel eligible: ${decision.conflictAssessment.parallelEligible ? "yes" : "no"}`,
    `- Routing posture: ${decision.conflictAssessment.routingPosture}`,
    `- Routing label: ${decision.conflictAssessment.routingLabel}`,
    ...decision.conflictAssessment.reasons.map((reason) => `- ${reason}`),
    "",
    ...renderSchedulerExecutionModeMarkdown(decision.schedulerExecutionMode),
    "",
    ...renderSchedulerLoopEvidenceSnapshotMarkdown(decision.schedulerLoopEvidenceSnapshot),
    "",
    "## Completion Audit",
    "",
    `- Status: ${decision.completionAudit.status}`,
    "",
    "### Evidence",
    "",
    ...(decision.completionAudit.evidence.length ? decision.completionAudit.evidence.map((item) => `- ${item}`) : ["- None."]),
    "",
    "### Missing",
    "",
    ...(decision.completionAudit.missing.length ? decision.completionAudit.missing.map((item) => `- ${item}`) : ["- None."]),
    "",
    "## Source Evidence",
    "",
    ...(decision.sourceEvidenceRefs.length
      ? decision.sourceEvidenceRefs.map((ref) => `- ${ref.kind}${ref.id ? ` ${ref.id}` : ""}${ref.status ? ` (${ref.status})` : ""}: ${ref.summary}`)
      : ["- None."]),
    "",
    "## Forbidden Actions",
    "",
    ...(decision.forbiddenActions.length
      ? decision.forbiddenActions.map((action) => `- ${action.actionType}: ${action.reason}`)
      : ["- None."]),
    "",
  ];
  return `${lines.join("\n")}\n`;
}

export function renderGoalLoopIterationMarkdown(iteration: GoalLoopIteration): string {
  const lines = [
    `# GoalLoopIteration ${iteration.id}`,
    "",
    `- Change: ${iteration.changeId}`,
    `- Ordinal: ${iteration.ordinal}`,
    `- Authority: ${iteration.authority}`,
    `- Trigger: ${iteration.trigger}`,
    `- Iteration status: ${iteration.iterationStatus}`,
    `- Continuation verdict: ${iteration.continuationVerdict}`,
    `- Continuation state: ${iteration.continuationState}`,
    `- GoalLoopDecision: ${iteration.goalLoopDecisionId}`,
    `- Previous iteration: ${iteration.previousGoalLoopIterationId ?? "none"}`,
    `- Previous decision: ${iteration.previousGoalLoopDecisionId ?? "none"}`,
    `- Human gate required: ${iteration.humanGateRequired ? "yes" : "no"}`,
    `- Execution started: ${iteration.executionStarted ? "yes" : "no"}`,
    "",
    "## Summary",
    "",
    iteration.summary,
    "",
    "## Recommended Action Snapshot",
    "",
    iteration.recommendedAction
      ? `- ${iteration.recommendedAction.actionType}: ${iteration.recommendedAction.reason}`
      : "- None.",
    ...(iteration.recommendedAction
      ? ["", "### Scope", "", ...Object.entries(iteration.recommendedAction.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`)]
      : []),
    "",
    "## Continuation Control Policy",
    "",
    `- Authority: ${iteration.controlPolicy.authority}`,
    `- Can auto-continue: ${iteration.controlPolicy.canAutoContinue ? "yes" : "no"}`,
    `- Can auto-execute recommended action: ${iteration.controlPolicy.canAutoExecuteRecommendedAction ? "yes" : "no"}`,
    `- Requires human gate: ${iteration.controlPolicy.requiresHumanGate ? "yes" : "no"}`,
    `- Recommended action type: ${iteration.controlPolicy.recommendedActionType ?? "none"}`,
    `- Reason: ${iteration.controlPolicy.reason}`,
    "",
    "## Budget / Accounting Signal",
    "",
    `- Status: ${iteration.budgetSignal.status}`,
    `- Summary: ${iteration.budgetSignal.summary}`,
    ...(iteration.budgetSignal.tokenBudget !== undefined ? [`- Token budget: ${iteration.budgetSignal.tokenBudget}`] : []),
    ...(iteration.budgetSignal.tokensUsed !== undefined ? [`- Tokens used: ${iteration.budgetSignal.tokensUsed}`] : []),
    ...(iteration.budgetSignal.remainingTokens !== undefined ? [`- Remaining tokens: ${iteration.budgetSignal.remainingTokens}`] : []),
    "",
    "## Resume Preconditions",
    "",
    ...(iteration.resumePreconditions.length
      ? iteration.resumePreconditions.map((item) => `- ${item.kind}${item.id ? ` ${item.id}` : ""}: ${item.satisfied ? "satisfied" : "pending"} - ${item.summary}`)
      : ["- None."]),
    "",
    "## Suppression Reason",
    "",
    iteration.suppressedBecause
      ? `- ${iteration.suppressedBecause.reason}: ${iteration.suppressedBecause.summary}`
      : "- None.",
    "",
    "## Conflict Assessment",
    "",
    `- Level: ${iteration.conflictAssessment.level}`,
    `- Parallel eligible: ${iteration.conflictAssessment.parallelEligible ? "yes" : "no"}`,
    `- Routing posture: ${iteration.conflictAssessment.routingPosture}`,
    `- Routing label: ${iteration.conflictAssessment.routingLabel}`,
    ...iteration.conflictAssessment.reasons.map((reason) => `- ${reason}`),
    "",
    ...renderSchedulerExecutionModeMarkdown(iteration.schedulerExecutionMode),
    "",
    "## Completion Audit",
    "",
    `- Status: ${iteration.completionAudit.status}`,
    "",
    "### Evidence",
    "",
    ...(iteration.completionAudit.evidence.length ? iteration.completionAudit.evidence.map((item) => `- ${item}`) : ["- None."]),
    "",
    "### Missing",
    "",
    ...(iteration.completionAudit.missing.length ? iteration.completionAudit.missing.map((item) => `- ${item}`) : ["- None."]),
    "",
    "## Source Evidence",
    "",
    ...(iteration.sourceEvidenceRefs.length
      ? iteration.sourceEvidenceRefs.map((ref) => `- ${ref.kind}${ref.id ? ` ${ref.id}` : ""}${ref.status ? ` (${ref.status})` : ""}: ${ref.summary}`)
      : ["- None."]),
    "",
    "## Boundary",
    "",
    "- This iteration is continuation evidence only.",
    "- It does not execute the recommended action.",
    "- Concrete next steps still require their own scoped Harness confirmation.",
    "",
  ];
  return `${lines.join("\n")}\n`;
}

export function renderGoalLoopContinuationBriefMarkdown(brief: GoalLoopContinuationBrief): string {
  const lines = [
    `# GoalLoopContinuationBrief ${brief.id}`,
    "",
    `- Change: ${brief.changeId}`,
    `- Authority: ${brief.authority}`,
    `- Source GoalLoopDecision: ${brief.sourceGoalLoopDecisionId}`,
    `- Source GoalLoopIteration: ${brief.sourceGoalLoopIterationId}`,
    `- Iteration ordinal: ${brief.iterationOrdinal}`,
    `- Decision: ${brief.decisionKind}`,
    `- Continuation verdict: ${brief.continuationVerdict}`,
    `- Continuation state: ${brief.continuationState}`,
    `- Human gate required: ${brief.humanGateRequired ? "yes" : "no"}`,
    `- Execution started: ${brief.executionStarted ? "yes" : "no"}`,
    "",
    "## Summary",
    "",
    brief.summary,
    "",
    "## Main Agent Instructions",
    "",
    ...brief.mainAgentInstructions.map((instruction) => `- ${instruction}`),
    "",
    "## Staleness / Re-read Instruction",
    "",
    brief.stalenessInstruction,
    "",
    "## Recommended Action Snapshot",
    "",
    brief.recommendedAction
      ? `- ${brief.recommendedAction.actionType}: ${brief.recommendedAction.reason}`
      : "- None.",
    ...(brief.recommendedAction
      ? ["", "### Scope", "", ...Object.entries(brief.recommendedAction.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`)]
      : []),
    "",
    "## Continuation Control Policy",
    "",
    `- Authority: ${brief.controlPolicy.authority}`,
    `- Can auto-continue: ${brief.controlPolicy.canAutoContinue ? "yes" : "no"}`,
    `- Can auto-execute recommended action: ${brief.controlPolicy.canAutoExecuteRecommendedAction ? "yes" : "no"}`,
    `- Requires human gate: ${brief.controlPolicy.requiresHumanGate ? "yes" : "no"}`,
    `- Recommended action type: ${brief.controlPolicy.recommendedActionType ?? "none"}`,
    `- Reason: ${brief.controlPolicy.reason}`,
    "",
    "## Budget / Accounting Signal",
    "",
    `- Status: ${brief.budgetSignal.status}`,
    `- Summary: ${brief.budgetSignal.summary}`,
    ...(brief.budgetSignal.tokenBudget !== undefined ? [`- Token budget: ${brief.budgetSignal.tokenBudget}`] : []),
    ...(brief.budgetSignal.tokensUsed !== undefined ? [`- Tokens used: ${brief.budgetSignal.tokensUsed}`] : []),
    ...(brief.budgetSignal.remainingTokens !== undefined ? [`- Remaining tokens: ${brief.budgetSignal.remainingTokens}`] : []),
    "",
    "## Resume Preconditions",
    "",
    ...(brief.resumePreconditions.length
      ? brief.resumePreconditions.map((item) => `- ${item.kind}${item.id ? ` ${item.id}` : ""}: ${item.satisfied ? "satisfied" : "pending"} - ${item.summary}`)
      : ["- None."]),
    "",
    "## Suppression Reason",
    "",
    brief.suppressedBecause
      ? `- ${brief.suppressedBecause.reason}: ${brief.suppressedBecause.summary}`
      : "- None.",
    "",
    "## Conflict Assessment",
    "",
    `- Level: ${brief.conflictAssessment.level}`,
    `- Parallel eligible: ${brief.conflictAssessment.parallelEligible ? "yes" : "no"}`,
    `- Routing posture: ${brief.conflictAssessment.routingPosture}`,
    `- Routing label: ${brief.conflictAssessment.routingLabel}`,
    ...brief.conflictAssessment.reasons.map((reason) => `- ${reason}`),
    "",
    ...renderSchedulerExecutionModeMarkdown(brief.schedulerExecutionMode),
    "",
    "## Completion Audit",
    "",
    `- Status: ${brief.completionAudit.status}`,
    "",
    "### Evidence",
    "",
    ...(brief.completionAudit.evidence.length ? brief.completionAudit.evidence.map((item) => `- ${item}`) : ["- None."]),
    "",
    "### Missing",
    "",
    ...(brief.completionAudit.missing.length ? brief.completionAudit.missing.map((item) => `- ${item}`) : ["- None."]),
    "",
    "## Source Evidence",
    "",
    ...(brief.sourceEvidenceRefs.length
      ? brief.sourceEvidenceRefs.map((ref) => `- ${ref.kind}${ref.id ? ` ${ref.id}` : ""}${ref.status ? ` (${ref.status})` : ""}: ${ref.summary}`)
      : ["- None."]),
    "",
    "## Forbidden Execution Statements",
    "",
    ...brief.forbiddenExecutionStatements.map((statement) => `- ${statement}`),
    "",
    "## Forbidden Actions",
    "",
    ...(brief.forbiddenActions.length
      ? brief.forbiddenActions.map((action) => `- ${action.actionType}: ${action.reason}`)
      : ["- None."]),
    "",
    "## Boundary",
    "",
    "- This brief is continuation handoff evidence only.",
    "- It is not a hidden next turn, scheduler loop, workflow truth, or execution authorization.",
    "- The next main Agent turn must re-read current Change evidence before relying on this brief.",
    "",
  ];
  return `${lines.join("\n")}\n`;
}

export function renderGoalLoopNextStepPacketMarkdown(packet: GoalLoopNextStepPacket): string {
  const lines = [
    `# GoalLoopNextStepPacket ${packet.id}`,
    "",
    `- Change: ${packet.changeId}`,
    `- Authority: ${packet.authority}`,
    `- Source GoalLoopDecision: ${packet.sourceGoalLoopDecisionId}`,
    `- Source GoalLoopIteration: ${packet.sourceGoalLoopIterationId}`,
    `- Source GoalLoopContinuationBrief: ${packet.sourceGoalLoopContinuationBriefId}`,
    `- Iteration ordinal: ${packet.iterationOrdinal}`,
    `- Decision: ${packet.decisionKind}`,
    `- Continuation verdict: ${packet.continuationVerdict}`,
    `- Continuation state: ${packet.continuationState}`,
    `- Recommendation state: ${packet.recommendationState}`,
    `- Separate gate required: ${packet.separateGateRequired ? "yes" : "no"}`,
    `- Human gate required: ${packet.humanGateRequired ? "yes" : "no"}`,
    `- Execution started: ${packet.executionStarted ? "yes" : "no"}`,
    "",
    "## Summary",
    "",
    packet.summary,
    "",
    "## Recommended Action Snapshot",
    "",
    packet.recommendedAction
      ? `- ${packet.recommendedAction.actionType}: ${packet.recommendedAction.reason}`
      : "- None.",
    ...(packet.recommendedAction
      ? ["", "### Scope", "", ...Object.entries(packet.recommendedAction.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`)]
      : []),
    "",
    "## Revalidation Checklist",
    "",
    ...packet.revalidationChecklist.map((item) => `- ${item}`),
    "",
    "## Main Agent Instructions",
    "",
    ...packet.mainAgentInstructions.map((item) => `- ${item}`),
    "",
    "## Staleness Instruction",
    "",
    packet.stalenessInstruction,
    "",
    "## Conflict Assessment",
    "",
    `- Level: ${packet.conflictAssessment.level}`,
    `- Parallel eligible: ${packet.conflictAssessment.parallelEligible ? "yes" : "no"}`,
    `- Routing posture: ${packet.conflictAssessment.routingPosture}`,
    `- Routing label: ${packet.conflictAssessment.routingLabel}`,
    ...packet.conflictAssessment.reasons.map((reason) => `- ${reason}`),
    "",
    ...renderSchedulerExecutionModeMarkdown(packet.schedulerExecutionMode),
    "",
    "## Completion Audit",
    "",
    `- Status: ${packet.completionAudit.status}`,
    "",
    "### Evidence",
    "",
    ...(packet.completionAudit.evidence.length ? packet.completionAudit.evidence.map((item) => `- ${item}`) : ["- None."]),
    "",
    "### Missing",
    "",
    ...(packet.completionAudit.missing.length ? packet.completionAudit.missing.map((item) => `- ${item}`) : ["- None."]),
    "",
    "## Source Evidence",
    "",
    ...(packet.sourceEvidenceRefs.length
      ? packet.sourceEvidenceRefs.map((ref) => `- ${ref.kind}${ref.id ? ` ${ref.id}` : ""}${ref.status ? ` (${ref.status})` : ""}: ${ref.summary}`)
      : ["- None."]),
    "",
    "## Forbidden Execution Statements",
    "",
    ...packet.forbiddenExecutionStatements.map((statement) => `- ${statement}`),
    "",
    "## Boundary",
    "",
    "- This packet is main-Agent resume context only.",
    "- It is not a hidden continuation turn, workflow truth, scheduler loop, or execution authorization.",
    "- Any recommended action must be revalidated and confirmed through its own scoped Harness gate.",
    "",
  ];
  return `${lines.join("\n")}\n`;
}

export function renderGoalLoopFeedbackMarkdown(feedback: GoalLoopFeedback): string {
  const quotedFeedback = feedback.feedbackText
    .split(/\r?\n/)
    .map((line) => `> ${line}`)
    .join("\n");
  const lines = [
    `# GoalLoopFeedback ${feedback.id}`,
    "",
    `- Change: ${feedback.changeId}`,
    `- Authority: ${feedback.authority}`,
    `- Source GoalLoopDecision: ${feedback.sourceGoalLoopDecisionId}`,
    `- Source GoalLoopIteration: ${feedback.sourceGoalLoopIterationId}`,
    `- Source GoalLoopContinuationBrief: ${feedback.sourceGoalLoopContinuationBriefId}`,
    `- Source GoalLoopNextStepPacket: ${feedback.sourceGoalLoopNextStepPacketId}`,
    `- Current gate action: ${feedback.currentGate.actionType}`,
    `- Execution started: ${feedback.executionStarted ? "yes" : "no"}`,
    "",
    "## Current Gate Scope",
    "",
    ...Object.entries(feedback.currentGate.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`),
    "",
    "## Recommended Action Snapshot",
    "",
    feedback.recommendedAction
      ? `- ${feedback.recommendedAction.actionType}: ${feedback.recommendedAction.reason}`
      : "- None.",
    "",
    "## User Feedback Evidence",
    "",
    quotedFeedback,
    "",
    "## Boundary",
    "",
    "- This feedback is quoted user evidence for the next Goal Loop evaluation.",
    "- It is not a hidden instruction, execution authorization, scheduler loop, or workflow truth.",
    "- The next evaluation must re-read current Change evidence and may only recommend existing scoped Harness gates.",
    "",
  ];
  return `${lines.join("\n")}\n`;
}

function renderSchedulerExecutionModeMarkdown(mode: GoalLoopDecision["schedulerExecutionMode"]): string[] {
  return [
    "## Scheduler Execution Mode",
    "",
    `- Authority: ${mode.authority}`,
    `- Mode: ${mode.mode}`,
    `- loopAuthorized: ${mode.loopAuthorized ? "true" : "false"}`,
    `- fullParallelExecutorAuthorized: ${mode.fullParallelExecutorAuthorized ? "true" : "false"}`,
    `- wholeWaveDispatchAuthorized: ${mode.wholeWaveDispatchAuthorized ? "true" : "false"}`,
    `- slotAllocatorAuthorized: ${mode.slotAllocatorAuthorized ? "true" : "false"}`,
    `- Human gate required: ${mode.humanGateRequired ? "yes" : "no"}`,
    ...(mode.currentGate ? [`- Current separate gate: ${mode.currentGate.actionType}`] : ["- Current separate gate: none"]),
    "",
    "### Summary",
    "",
    mode.summary,
    "",
    "### Reasons",
    "",
    ...mode.reasons.map((reason) => `- ${reason}`),
    "",
    "### Future Loop Requirements",
    "",
    ...mode.futureLoopRequirements.map((requirement) => `- ${requirement}`),
    "",
    "### Boundary",
    "",
    "- Scheduler execution mode is evidence only.",
    "- It does not execute, prioritize, or confirm scheduler actions.",
    "- A real scheduler loop or full parallel executor requires a later accepted design and implementation phase.",
  ];
}

function renderSchedulerLoopEvidenceSnapshotMarkdown(snapshot: GoalLoopDecision["schedulerLoopEvidenceSnapshot"]): string[] {
  return [
    "## Scheduler Loop Evidence Snapshot",
    "",
    "- This snapshot is non-executing evidence only; it does not authorize a scheduler loop or invoke a concrete gate.",
    `- Authority: ${snapshot.authority}`,
    `- Posture: ${snapshot.posture}`,
    `- Planning complete: ${snapshot.planningComplete ? "yes" : "no"}`,
    `- Decision kind: ${snapshot.decisionKind}`,
    `- Human gate required: ${snapshot.humanGateRequired ? "yes" : "no"}`,
    `- Separate human gate required: ${snapshot.separateHumanGateRequired ? "yes" : "no"}`,
    snapshot.currentLegalAction
      ? `- Current legal action: ${snapshot.currentLegalAction.actionType}`
      : "- Current legal action: none",
    `- loopAuthorized: ${snapshot.forbiddenAuthority.loopAuthorized ? "true" : "false"}`,
    `- fullParallelExecutorAuthorized: ${snapshot.forbiddenAuthority.fullParallelExecutorAuthorized ? "true" : "false"}`,
    `- wholeWaveDispatchAuthorized: ${snapshot.forbiddenAuthority.wholeWaveDispatchAuthorized ? "true" : "false"}`,
    `- slotAllocatorAuthorized: ${snapshot.forbiddenAuthority.slotAllocatorAuthorized ? "true" : "false"}`,
    `- sourceMutationAuthorized: ${snapshot.forbiddenAuthority.sourceMutationAuthorized ? "true" : "false"}`,
    `- applyAuthorized: ${snapshot.forbiddenAuthority.applyAuthorized ? "true" : "false"}`,
    `- closeAuthorized: ${snapshot.forbiddenAuthority.closeAuthorized ? "true" : "false"}`,
    `- harnessEvolutionAuthorized: ${snapshot.forbiddenAuthority.harnessEvolutionAuthorized ? "true" : "false"}`,
    "",
    "### Snapshot Reasons",
    "",
    ...(snapshot.reasons.length ? snapshot.reasons.map((reason) => `- ${reason}`) : ["- None."]),
    "",
    "### Unsafe Evidence",
    "",
    ...(snapshot.unsafeEvidence.length
      ? snapshot.unsafeEvidence.map((evidence) => `- ${evidence.kind}${evidence.artifactId ? ` ${evidence.artifactId}` : ""}: ${evidence.summary}`)
      : ["- None."]),
  ];
}

export function renderGoalLoopFeedbackAcknowledgementMarkdown(feedback: GoalLoopFeedback): string {
  const excerpt = feedback.feedbackText.replace(/\s+/g, " ").trim();
  const clipped = excerpt.length > 240 ? `${excerpt.slice(0, 237)}...` : excerpt;
  const lines = [
    "## Goal Loop feedback recorded",
    "",
    `Feedback: "${clipped}"`,
    "",
    `- Feedback evidence: ${feedback.id}`,
    `- Source packet: ${feedback.sourceGoalLoopNextStepPacketId}`,
    `- Current gate: ${feedback.currentGate.actionType}`,
    "- A fresh Goal Loop evaluation was recorded after this feedback.",
    "- No recommendation was executed; the concrete Harness gate still requires its own confirmation.",
    "",
  ];
  return `${lines.join("\n")}\n`;
}

export function renderGoalLoopControllerPolicyMarkdown(policy: GoalLoopControllerPolicy): string {
  const lines = [
    `# GoalLoopControllerPolicy ${policy.id}`,
    "",
    `- Change: ${policy.changeId}`,
    `- Authority: ${policy.authority}`,
    `- Source GoalLoopDecision: ${policy.sourceGoalLoopDecisionId}`,
    `- Source GoalLoopIteration: ${policy.sourceGoalLoopIterationId}`,
    `- Source GoalLoopContinuationBrief: ${policy.sourceGoalLoopContinuationBriefId}`,
    `- Source GoalLoopNextStepPacket: ${policy.sourceGoalLoopNextStepPacketId}`,
    `- Iteration ordinal: ${policy.iterationOrdinal}`,
    `- Verdict: ${policy.verdict}`,
    `- Gate status: ${policy.gateStatus}`,
    `- Human gate required: ${policy.humanGateRequired ? "yes" : "no"}`,
    `- Suppresses recommended action: ${policy.suppressesRecommendedAction ? "yes" : "no"}`,
    `- Execution started: ${policy.executionStarted ? "yes" : "no"}`,
    "",
    "## Summary",
    "",
    policy.summary,
    "",
    "## Recommended Action Snapshot",
    "",
    policy.recommendedAction
      ? `- ${policy.recommendedAction.actionType}: ${policy.recommendedAction.reason}`
      : "- None.",
    ...(policy.recommendedAction
      ? ["", "### Scope", "", ...Object.entries(policy.recommendedAction.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`)]
      : []),
    "",
    "## Current Gate Snapshot",
    "",
    policy.currentGate
      ? `- ${policy.currentGate.actionType}`
      : "- None.",
    ...(policy.currentGate
      ? ["", "### Scope", "", ...Object.entries(policy.currentGate.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`)]
      : []),
    "",
    ...renderSchedulerExecutionModeMarkdown(policy.schedulerExecutionMode),
    "",
    "## Revalidation Checklist",
    "",
    ...policy.revalidationChecklist.map((item) => `- ${item}`),
    "",
    "## Forbidden Execution Statements",
    "",
    ...policy.forbiddenExecutionStatements.map((statement) => `- ${statement}`),
    "",
    "## Boundary",
    "",
    "- This controller policy is non-executing evidence only.",
    "- It may explain whether the main Agent should recommend the existing gate, wait, suppress stale guidance, or report blocked state.",
    "- It must not call action handlers, start workers, run validation/audit/IntegrationCheck, mutate source, close/apply, or bypass ToolPolicyGate/human gates.",
    "",
  ];
  return `${lines.join("\n")}\n`;
}

export function renderGoalLoopGateReadinessPreflightMarkdown(preflight: GoalLoopGateReadinessPreflight): string {
  const lines = [
    `# GoalLoopGateReadinessPreflight ${preflight.id}`,
    "",
    `- Change: ${preflight.changeId}`,
    `- Authority: ${preflight.authority}`,
    `- Status: ${preflight.status}`,
    `- Source GoalLoopDecision: ${preflight.sourceGoalLoopDecisionId}`,
    `- Source GoalLoopIteration: ${preflight.sourceGoalLoopIterationId}`,
    `- Source GoalLoopContinuationBrief: ${preflight.sourceGoalLoopContinuationBriefId}`,
    `- Source GoalLoopNextStepPacket: ${preflight.sourceGoalLoopNextStepPacketId}`,
    `- Source GoalLoopControllerPolicy: ${preflight.sourceGoalLoopControllerPolicyId}`,
    `- Current gate: ${preflight.currentGate.actionType}`,
    `- Human gate required: ${preflight.humanGateRequired ? "yes" : "no"}`,
    `- Concrete gate invoked: ${preflight.concreteGateInvoked ? "yes" : "no"}`,
    `- ToolPolicy authorized concrete gate: ${preflight.toolPolicyAuthorizedConcreteGate ? "yes" : "no"}`,
    `- Execution started: ${preflight.executionStarted ? "yes" : "no"}`,
    "",
    "## Summary",
    "",
    preflight.summary,
    "",
    ...renderSchedulerExecutionModeMarkdown(preflight.schedulerExecutionMode),
    "",
    "## Concrete Gate Scope",
    "",
    ...Object.entries(preflight.currentGate.scope).map(([key, value]) => `- ${key}: ${Array.isArray(value) ? value.join(", ") : value}`),
    "",
    "## Required Targets Checked",
    "",
    ...(preflight.requiredTargetLabels.length ? preflight.requiredTargetLabels.map((label) => `- ${label}`) : ["- None."]),
    "",
    "## Revalidation Checklist",
    "",
    ...preflight.revalidationChecklist.map((item) => `- ${item}`),
    "",
    "## Forbidden Execution Statements",
    "",
    ...preflight.forbiddenExecutionStatements.map((statement) => `- ${statement}`),
    "",
    "## Boundary",
    "",
    "- This preflight is readiness evidence only.",
    "- It does not call the concrete Workbench action handler.",
    "- The concrete gate still requires its own stale-target revalidation, ToolPolicyGate, and human confirmation.",
    "- It must not mutate source, start workers, create runs/worktrees/TaskRuns/IntegrationChecks, apply, close, merge, or create child Changes.",
    "",
  ];
  return `${lines.join("\n")}\n`;
}
