export function workflowActionLabel(actionType: string | undefined): string {
  if (actionType === "change.spec.propose") return "Spec proposal";
  if (actionType === "change.plan.propose") return "Plan/Tasks proposal";
  if (actionType === "planning.generate") return "生成方案草案";
  if (actionType === "planning.revise") return "修改方案草案";
  if (actionType === "planning.confirm-execution") return "确认规划";
  if (actionType === "planning.decompose") return "拆分评估";
  if (actionType === "planning.decomposition.confirm") return "确认拆分方向";
  if (actionType === "planning.decomposition.assess-readiness") return "检查执行边界";
  if (actionType === "taskqueue.proposal") return "TaskQueue proposal";
  if (actionType === "scheduler.contract") return "Scheduler Contract";
  if (actionType === "planning.taskqueue.propose") return "生成 TaskQueue 提案";
  if (actionType === "planning.scheduler.contract.compile") return "编译 Scheduler Contract";
  if (actionType === "planning.scheduler.dispatch.dry-run") return "生成调度预演";
  if (actionType === "planning.scheduler.worker-plan.compile") return "编译 Worker Session Plan";
  if (actionType === "planning.scheduler.claim-reconcile.compile") return "编译 Claim / Reconcile Plan";
  if (actionType === "planning.scheduler.launch-preflight.check") return "检查 Launch Preflight";
  if (actionType === "planning.scheduler.run.prepare") return "准备调度运行记录";
  if (actionType === "planning.scheduler.runtime.initialize") return "初始化 Scheduler Runtime 壳";
  if (actionType === "planning.scheduler.runtime.reconcile") return "生成 Reconcile Snapshot";
  if (actionType === "planning.scheduler.runtime.reserve-claims") return "预占 Runtime Claims";
  if (actionType === "planning.workflowgraph.compile") return "编译执行图";
  if (actionType === "planning.taskqueue.confirm-start") return "确认启动 TaskQueue";
  if (actionType === "none") return "无后续动作";
  if (actionType === "orchestrator.evaluate") return "检查处理状态";
  if (actionType === "orchestrator.pump") return "继续处理需求";
  if (actionType === "demand.worker.enqueue") return "加入处理队列";
  if (actionType === "demand.worker.claim") return "领取需求";
  if (actionType === "demand.worker.start-next") return "开始处理";
  if (actionType === "demand.worker.start-available") return "开始可处理需求";
  if (actionType === "demand.worker.reconcile") return "恢复处理状态";
  if (actionType === "demand.worker.release") return "结束处理";
  if (actionType === "role.pipeline.start") return "角色流水线";
  if (actionType === "role.pipeline.stop") return "停止当前执行";
  if (actionType === "conversation.steer") return "引导当前执行";
  if (actionType === "conversation.interrupt") return "停止当前执行";
  if (actionType === "conversation.continue") return "继续执行";
  if (actionType === "result.refresh-rework") return "重新处理这个结果";
  if (actionType === "result.revalidate") return "重新验证";
  if (actionType === "result.reaudit") return "重新审查";
  if (actionType === "result.refresh-status") return "刷新状态";
  if (actionType === "apply-check.run") return "检查兼容性";
  if (actionType === "landing.prepare") return "提交/PR 前检查";
  if (actionType === "landing.review") return "审查落地检查";
  if (actionType === "landing.refresh") return "刷新落地检查";
  if (actionType === "landing-queue.prepare") return "检查合并队列";
  if (actionType === "landing-queue.refresh") return "刷新合并队列";
  if (actionType === "landing-queue.merge-next") return "合并 PR";
  if (actionType === "landing-queue.skip") return "跳过这个 PR";
  if (actionType === "landing-queue.remove-stale") return "移出过期项";
  if (actionType === "pr-draft.prepare") return "准备 PR 草稿";
  if (actionType === "pr-draft.create") return "创建 PR 草稿";
  if (actionType === "pr-draft.refresh") return "刷新 PR 状态";
  if (actionType === "pr-feedback.refresh") return "检查 PR 反馈";
  if (actionType === "pr-feedback.evaluate") return "分析 PR 反馈";
  if (actionType === "pr-feedback.rework") return "根据 PR 反馈修改";
  if (actionType === "pr-feedback.update-draft") return "更新 PR 草稿";
  if (actionType === "pr-review.prepare") return "准备人工评审";
  if (actionType === "pr-review.submit") return "提交人工评审";
  if (actionType === "pr-review.refresh") return "刷新评审状态";
  if (actionType === "pr-review.feedback-refresh") return "检查评审反馈";
  if (actionType === "pr-review.feedback-evaluate") return "分析评审反馈";
  if (actionType === "pr-review.rework") return "根据评审修改";
  if (actionType === "pr-review.reply-prepare") return "准备评审回复";
  if (actionType === "pr-review.reply-submit") return "回复评审";
  if (actionType === "pr-review.thread-resolve") return "标记已处理";
  if (actionType === "remote-landing.prepare") return "检查合并状态";
  if (actionType === "remote-landing.merge") return "合并 PR";
  if (actionType === "remote-landing.refresh") return "刷新合并状态";
  if (actionType === "post-merge.prepare") return "检查合并后状态";
  if (actionType === "post-merge.refresh") return "刷新合并后状态";
  if (actionType === "post-merge.sync-local.prepare") return "检查本地同步";
  if (actionType === "post-merge.sync-local.run") return "同步本地项目";
  if (actionType === "post-merge.cleanup-branch.prepare") return "检查远端分支";
  if (actionType === "post-merge.cleanup-branch.run") return "清理远端 PR 分支";
  if (actionType === "role.pipeline.continue") return "继续执行";
  if (actionType === "role.pipeline.reconcile") return "恢复执行状态";
  if (actionType === "code.run") return "Code workflow";
  if (actionType === "task.run.start") return "Task workflow";
  if (actionType === "task.run.retry") return "Retry task";
  if (actionType === "chat.ask") return "Chat";
  return actionType ?? "Workflow";
}
