import type { SchedulerClaimReconcilePlan, SchedulerContract, SchedulerDispatchDryRun, SchedulerLaunchPreflight, SchedulerRun, SchedulerWorkerSessionPlan } from "./types.js";

export function renderSchedulerContractMarkdown(contract: SchedulerContract): string {
  const lines = [
    `# SchedulerContract ${contract.id}`,
    "",
    `Status: ${contract.status}`,
    `Mode: ${contract.schedulerMode}`,
    `Change: ${contract.changeId}`,
    `DecompositionPlan: ${contract.decompositionPlanId}`,
    `ReadinessManifest: ${contract.readinessManifestId}`,
    "",
    "## Summary",
    "",
    `- Nodes: ${contract.nodes.length}`,
    `- Edges: ${contract.edges.length}`,
    `- Waves: ${contract.waves.length}`,
    `- Conflict scopes: ${contract.conflictScopes.length}`,
    "",
    "## Waves",
    "",
    ...contract.waves.map((wave) => `- Wave ${wave.index + 1}: ${wave.nodeIds.join(", ")}`),
    "",
    "## Nodes",
    "",
    ...contract.nodes.map((node) => [
      `### ${node.id}`,
      "",
      `- Unit: ${node.unitId}`,
      `- Title: ${node.title}`,
      `- Tasks: ${node.taskIds.join(", ") || "none"}`,
      `- ACs: ${node.acIds.join(", ") || "none"}`,
      `- Source scopes: ${node.sourceScopes.join(", ") || "none"}`,
      `- Stages: ${node.stages.join(" -> ")}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This SchedulerContract is non-executing evidence. It does not create TaskRuns, WorkerLeases, worktrees, runs, child Changes, or source mutations.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerDispatchDryRunMarkdown(dryRun: SchedulerDispatchDryRun): string {
  const lines = [
    `# SchedulerDispatchDryRun ${dryRun.id}`,
    "",
    `Status: ${dryRun.status}`,
    `Mode: ${dryRun.schedulerMode}`,
    `Change: ${dryRun.changeId}`,
    `SchedulerContract: ${dryRun.schedulerContractId}`,
    `DecompositionPlan: ${dryRun.decompositionPlanId}`,
    `ReadinessManifest: ${dryRun.readinessManifestId}`,
    "",
    "## Summary",
    "",
    `- Waves: ${dryRun.waveVerdicts.length}`,
    `- Nodes: ${dryRun.nodeVerdicts.length}`,
    `- Dependencies: ${dryRun.dependencyCount}`,
    `- Conflict scopes: ${dryRun.conflictCount}`,
    `- Estimated max wave width: ${dryRun.estimatedMaxWaveWidth}`,
    `- Blocked reasons: ${dryRun.blockedReasons.length ? dryRun.blockedReasons.join("; ") : "none"}`,
    "",
    "## Runtime Continuity Prerequisites",
    "",
    ...dryRun.runtimeContinuityPrerequisites.map((item) => `- ${item}`),
    "",
    "## Wave Verdicts",
    "",
    ...dryRun.waveVerdicts.map((wave) => [
      `### Wave ${wave.index + 1}`,
      "",
      `- Status: ${wave.status}`,
      `- Candidate nodes: ${wave.candidateCount}`,
      `- Blocked nodes: ${wave.blockedCount}`,
      `- Nodes: ${wave.nodeIds.join(", ") || "none"}`,
      `- Blocked reasons: ${wave.blockedReasons.length ? wave.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Node Verdicts",
    "",
    ...dryRun.nodeVerdicts.map((node) => [
      `### ${node.nodeId}`,
      "",
      `- Unit: ${node.unitId}`,
      `- Wave: ${node.waveIndex + 1}`,
      `- Status: ${node.status}`,
      `- Dependencies satisfied: ${node.dependenciesSatisfied ? "yes" : "no"}`,
      `- Dependency nodes: ${node.dependencyNodeIds.join(", ") || "none"}`,
      `- Source scopes: ${node.sourceScopes.join(", ") || "none"}`,
      `- Stages: ${node.stages.join(" -> ")}`,
      `- Blocked reasons: ${node.blockedReasons.length ? node.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This dry-run is non-executing evidence. It does not allocate DemandWorker slots, create WorkerLeases, create TaskRuns, create WorkflowRuns, start agents, create worktrees, create runs, create child Changes, or mutate source.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerWorkerSessionPlanMarkdown(plan: SchedulerWorkerSessionPlan): string {
  const lines = [
    `# SchedulerWorkerSessionPlan ${plan.id}`,
    "",
    `Status: ${plan.status}`,
    `Mode: ${plan.schedulerMode}`,
    `Change: ${plan.changeId}`,
    `SchedulerContract: ${plan.schedulerContractId}`,
    `SchedulerDispatchDryRun: ${plan.schedulerDispatchDryRunId}`,
    `DecompositionPlan: ${plan.decompositionPlanId}`,
    `ReadinessManifest: ${plan.readinessManifestId}`,
    "",
    "## Summary",
    "",
    `- Planned workers: ${plan.plannedWorkerCount}`,
    `- Stages: ${plan.stageCount}`,
    `- Nodes: ${plan.plannedNodes.length}`,
    `- Blocked entries: ${plan.blockedCount}`,
    `- Warnings: ${plan.warningCount}`,
    `- Recovery key coverage: ${plan.recoveryKeyCoverage}`,
    "",
    "## Nodes",
    "",
    ...plan.plannedNodes.map((node) => [
      `### ${node.nodeId}`,
      "",
      `- Unit: ${node.unitId}`,
      `- Wave: ${node.waveIndex + 1}`,
      `- Status: ${node.status}`,
      `- Stage plans: ${node.stageIds.join(", ") || "none"}`,
      `- Blocked reasons: ${node.blockedReasons.length ? node.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Stage Worker Plans",
    "",
    ...plan.plannedStages.map((stage) => [
      `### ${stage.id}`,
      "",
      `- Node: ${stage.nodeId}`,
      `- Stage: ${stage.stage}`,
      `- Role: ${stage.roleId}`,
      `- Adapter family: ${stage.adapterFamily}`,
      `- Workspace: ${stage.workspaceIntent.kind}`,
      `- Source scopes: ${stage.workspaceIntent.sourceScopes.join(", ") || "none"}`,
      `- Sandbox policy: ${stage.permissionProfile.sandboxPolicy}`,
      `- Event source: ${stage.eventSourceExpectation.adapterFamily}`,
      `- Recovery keys: ${stage.recoveryKeyInputs.map((item) => item.key).join(", ") || "none"}`,
      `- Blocked reasons: ${stage.blockedReasons.length ? stage.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This worker session plan is non-executing evidence. It does not create Runtime Continuity sidecars, TaskRuns, WorkerLeases, AgentTasks, worktrees, runs, child Changes, or scheduler loops.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerClaimReconcilePlanMarkdown(plan: SchedulerClaimReconcilePlan): string {
  const lines = [
    `# SchedulerClaimReconcilePlan ${plan.id}`,
    "",
    `Status: ${plan.status}`,
    `Mode: ${plan.schedulerMode}`,
    `Change: ${plan.changeId}`,
    `SchedulerContract: ${plan.schedulerContractId}`,
    `SchedulerDispatchDryRun: ${plan.schedulerDispatchDryRunId}`,
    `SchedulerWorkerSessionPlan: ${plan.schedulerWorkerPlanId}`,
    `DecompositionPlan: ${plan.decompositionPlanId}`,
    `ReadinessManifest: ${plan.readinessManifestId}`,
    "",
    "## Summary",
    "",
    `- Claim intents: ${plan.claimIntents.length}`,
    `- Waves: ${plan.waveCheckpoints.length}`,
    `- Planned slot demand: ${plan.plannedSlotDemand}`,
    `- Max planned wave width: ${plan.maxPlannedWaveWidth}`,
    `- Blocked entries: ${plan.blockedCount}`,
    `- Recovery key coverage: ${plan.recoveryKeyCoverage}`,
    "",
    "## Wave Reconcile Checkpoints",
    "",
    ...plan.waveCheckpoints.map((wave) => [
      `### Wave ${wave.waveIndex + 1}`,
      "",
      `- Claim intents: ${wave.claimIntentIds.join(", ") || "none"}`,
      `- Candidate claims: ${wave.candidateCount}`,
      `- Blocked claims: ${wave.blockedCount}`,
      `- Planned slot demand: ${wave.plannedSlotDemand}`,
      `- Blocked reasons: ${wave.blockedReasons.length ? wave.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Claim Intents",
    "",
    ...plan.claimIntents.map((claim) => [
      `### ${claim.claimIntentId}`,
      "",
      `- Planned worker key: ${claim.plannedWorkerKey}`,
      `- Node: ${claim.nodeId}`,
      `- Unit: ${claim.unitId}`,
      `- Wave: ${claim.waveIndex + 1}`,
      `- Status: ${claim.status}`,
      `- Stages: ${claim.stageIds.join(", ") || "none"}`,
      `- Roles: ${claim.roleIds.join(", ") || "none"}`,
      `- Source scopes: ${claim.sourceScopes.join(", ") || "none"}`,
      `- Planned slot demand: ${claim.plannedSlotDemand}`,
      `- Source lock intents: ${claim.sourceLockIntents.map((intent) => intent.scope).join(", ") || "none"}`,
      `- Recovery keys: ${claim.recoveryKeyInputs.map((item) => item.key).join(", ") || "none"}`,
      `- Blocked reasons: ${claim.blockedReasons.length ? claim.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This claim/reconcile plan is non-executing evidence. It does not create WorkerLeases, WorkerSessions, Runtime Continuity sidecars, TaskRuns, AgentTasks, worktrees, runs, child Changes, scheduler loops, slot allocators, or parallel execution authorization.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerLaunchPreflightMarkdown(preflight: SchedulerLaunchPreflight): string {
  const lines = [
    `# SchedulerLaunchPreflight ${preflight.id}`,
    "",
    `Status: ${preflight.status}`,
    `Mode: ${preflight.schedulerMode}`,
    `Change: ${preflight.changeId}`,
    `SchedulerContract: ${preflight.schedulerContractId}`,
    `SchedulerDispatchDryRun: ${preflight.schedulerDispatchDryRunId}`,
    `SchedulerWorkerSessionPlan: ${preflight.schedulerWorkerPlanId}`,
    `SchedulerClaimReconcilePlan: ${preflight.schedulerClaimReconcilePlanId}`,
    `DecompositionPlan: ${preflight.decompositionPlanId}`,
    `ReadinessManifest: ${preflight.readinessManifestId}`,
    "",
    "## Summary",
    "",
    `- Claim intents: ${preflight.claimSummaries.length}`,
    `- Planned slot demand: ${preflight.plannedSlotDemand}`,
    `- Max planned wave width: ${preflight.maxPlannedWaveWidth}`,
    `- Blocked entries: ${preflight.blockedCount}`,
    `- ToolPolicyGate requirement: ${preflight.toolPolicyGateRequirement.status}`,
    `- Human gate requirement: ${preflight.humanGateRequirement.status}`,
    `- Blocked reasons: ${preflight.blockedReasons.length ? preflight.blockedReasons.join("; ") : "none"}`,
    "",
    "## Runtime Continuity Requirements",
    "",
    ...preflight.runtimeContinuityRequirements.map((item) => `- ${item.id}: ${item.status} - ${item.description}`),
    "",
    "## Permission Requirements",
    "",
    ...preflight.permissionProfileRequirements.map((item) => `- ${item.id}: ${item.status} - ${item.description}`),
    "",
    "## Source Locks",
    "",
    ...preflight.sourceLockSummaries.map((lock) => [
      `### ${lock.scope}`,
      "",
      `- Status: ${lock.status}`,
      `- Waves: ${lock.waveIndexes.map((index) => String(index + 1)).join(", ") || "none"}`,
      `- Claim intents: ${lock.claimIntentIds.join(", ") || "none"}`,
      `- Blocked reasons: ${lock.blockedReasons.length ? lock.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Claim Intent Summaries",
    "",
    ...preflight.claimSummaries.map((claim) => [
      `### ${claim.claimIntentId}`,
      "",
      `- Planned worker key: ${claim.plannedWorkerKey}`,
      `- Node: ${claim.nodeId}`,
      `- Unit: ${claim.unitId}`,
      `- Wave: ${claim.waveIndex + 1}`,
      `- Status: ${claim.status}`,
      `- Planned slot demand: ${claim.plannedSlotDemand}`,
      `- Source scopes: ${claim.sourceScopes.join(", ") || "none"}`,
      `- Blocked reasons: ${claim.blockedReasons.length ? claim.blockedReasons.join("; ") : "none"}`,
      "",
    ].join("\n")),
    "## Boundary",
    "",
    "This launch preflight is non-executing evidence. Status `checked` is not execution authorization. A future executor must re-run ToolPolicyGate and require a human gate before creating WorkerLeases, WorkerSessions, Runtime Continuity sidecars, TaskRuns, WorkflowRuns, worktrees, runs, child Changes, scheduler loops, slot allocators, or parallel execution.",
    "",
  ];
  return lines.join("\n");
}

export function renderSchedulerRunMarkdown(run: SchedulerRun): string {
  const lines = [
    `# SchedulerRun ${run.id}`,
    "",
    `Status: ${run.status}`,
    `Mode: ${run.schedulerMode}`,
    `Change: ${run.changeId}`,
    `SchedulerContract: ${run.schedulerContractId}`,
    `SchedulerDispatchDryRun: ${run.schedulerDispatchDryRunId}`,
    `SchedulerWorkerSessionPlan: ${run.schedulerWorkerPlanId}`,
    `SchedulerClaimReconcilePlan: ${run.schedulerClaimReconcilePlanId}`,
    `SchedulerLaunchPreflight: ${run.schedulerLaunchPreflightId}`,
    `DecompositionPlan: ${run.decompositionPlanId}`,
    `ReadinessManifest: ${run.readinessManifestId}`,
    "",
    "## Summary",
    "",
    `- Claim intents: ${run.claimIntentCount}`,
    `- Planned slot demand: ${run.plannedSlotDemand}`,
    `- Max planned wave width: ${run.maxPlannedWaveWidth}`,
    `- Blocked entries: ${run.blockedCount}`,
    `- Human confirmed: ${run.humanConfirmed ? "yes" : "no"}`,
    `- Future ToolPolicyGate required: ${run.futureToolPolicyGateRequired ? "yes" : "no"}`,
    `- Future human gate required: ${run.futureHumanGateRequired ? "yes" : "no"}`,
    "",
    "## Journal",
    "",
    `- Journal artifact: ${run.journalArtifact}`,
    "",
    "## Boundary",
    "",
    "This SchedulerRun is a journal shell. Status `prepared` is not execution authorization, and status `completed` only records terminal scheduler recovery/projection evidence after existing integration/apply/discard gates have produced terminal outcome evidence.",
    "",
    "It does not create WorkerLeases, WorkerSessions, Runtime Continuity sidecars, TaskRuns, WorkflowRuns, worktrees, runs, child Changes, scheduler loops, slot allocators, or parallel execution.",
    "",
  ];
  return lines.join("\n");
}
