import { z } from "zod";
import type { SchedulerClaimReconcilePlan, SchedulerContract, SchedulerDispatchDryRun, SchedulerLaunchPreflight, SchedulerRun, SchedulerRunJournalEvent, SchedulerWorkerSessionPlan } from "./types.js";

const workerPermissionProfileSchema = z.object({
  version: z.literal("1.0"),
  roleId: z.string(),
  allowedReadRoots: z.array(z.string()),
  allowedWriteRoots: z.array(z.string()),
  deniedPaths: z.array(z.string()),
  allowedCommands: z.array(z.string()),
  sandboxPolicy: z.enum(["read-only", "workspace-write"]),
  mayDelegate: z.boolean(),
});

export const schedulerContractSchema: z.ZodType<SchedulerContract> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  status: z.enum(["compiled", "superseded", "rejected"]),
  schedulerMode: z.literal("parallel-readiness-v1"),
  workflowGraphPlanId: z.string(),
  nodes: z.array(z.object({
    id: z.string(),
    unitId: z.string(),
    taskIds: z.array(z.string()),
    acIds: z.array(z.string()),
    title: z.string(),
    sourceScopes: z.array(z.string()),
    stages: z.array(z.enum(["coder", "validation", "audit", "bounded-rework"])),
  })),
  edges: z.array(z.object({
    from: z.string(),
    to: z.string(),
    kind: z.enum(["dependency", "synthesis"]),
  })),
  waves: z.array(z.object({
    index: z.number(),
    nodeIds: z.array(z.string()),
  })),
  conflictScopes: z.array(z.string()),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerDispatchDryRunSchema: z.ZodType<SchedulerDispatchDryRun> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  status: z.enum(["generated", "superseded", "rejected"]),
  schedulerMode: z.literal("parallel-readiness-v1"),
  schedulerContractId: z.string(),
  workflowGraphPlanId: z.string(),
  nodeVerdicts: z.array(z.object({
    nodeId: z.string(),
    unitId: z.string(),
    waveIndex: z.number(),
    status: z.enum(["candidate", "blocked"]),
    dependencyNodeIds: z.array(z.string()),
    dependenciesSatisfied: z.boolean(),
    sourceScopes: z.array(z.string()),
    stages: z.array(z.enum(["coder", "validation", "audit", "bounded-rework"])),
    runtimeContinuityPrerequisites: z.array(z.string()),
    blockedReasons: z.array(z.string()),
  })),
  waveVerdicts: z.array(z.object({
    index: z.number(),
    nodeIds: z.array(z.string()),
    status: z.enum(["candidate", "blocked"]),
    candidateCount: z.number(),
    blockedCount: z.number(),
    blockedReasons: z.array(z.string()),
  })),
  estimatedMaxWaveWidth: z.number(),
  dependencyCount: z.number(),
  conflictCount: z.number(),
  conflictScopes: z.array(z.string()),
  runtimeContinuityPrerequisites: z.array(z.string()),
  blockedReasons: z.array(z.string()),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerWorkerSessionPlanSchema: z.ZodType<SchedulerWorkerSessionPlan> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  status: z.enum(["planned", "superseded", "rejected"]),
  schedulerMode: z.literal("parallel-readiness-v1"),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  workflowGraphPlanId: z.string(),
  plannedNodes: z.array(z.object({
    nodeId: z.string(),
    unitId: z.string(),
    waveIndex: z.number(),
    status: z.enum(["planned", "blocked"]),
    stageIds: z.array(z.string()),
    blockedReasons: z.array(z.string()),
  })),
  plannedStages: z.array(z.object({
    id: z.string(),
    nodeId: z.string(),
    unitId: z.string(),
    waveIndex: z.number(),
    stage: z.enum(["coder", "validation", "audit", "bounded-rework"]),
    roleId: z.string(),
    status: z.enum(["planned", "blocked"]),
    workspaceIntent: z.object({
      kind: z.literal("future-local-worktree"),
      sourceScopes: z.array(z.string()),
      requiresFreshWorktree: z.boolean(),
    }),
    adapterFamily: z.enum(["codex-code", "validation-command", "audit-codex-readonly"]),
    permissionProfile: workerPermissionProfileSchema,
    eventSourceExpectation: z.object({
      adapterFamily: z.enum(["codex-code", "validation-command", "audit-codex-readonly"]),
      expectedEventTypes: z.array(z.string()),
    }),
    recoveryKeyInputs: z.array(z.object({
      key: z.string(),
      value: z.union([z.string(), z.array(z.string())]),
    })),
    blockedReasons: z.array(z.string()),
  })),
  plannedWorkerCount: z.number(),
  stageCount: z.number(),
  blockedCount: z.number(),
  warningCount: z.number(),
  recoveryKeyCoverage: z.enum(["complete", "partial"]),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerClaimReconcilePlanSchema: z.ZodType<SchedulerClaimReconcilePlan> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  status: z.enum(["planned", "superseded", "rejected"]),
  schedulerMode: z.literal("parallel-readiness-v1"),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  workflowGraphPlanId: z.string(),
  claimIntents: z.array(z.object({
    claimIntentId: z.string(),
    plannedWorkerKey: z.string(),
    nodeId: z.string(),
    unitId: z.string(),
    waveIndex: z.number(),
    stageIds: z.array(z.string()),
    roleIds: z.array(z.string()),
    sourceScopes: z.array(z.string()),
    status: z.enum(["planned", "blocked"]),
    plannedSlotDemand: z.number(),
    sourceLockIntents: z.array(z.object({
      scope: z.string(),
      nodeId: z.string(),
      unitId: z.string(),
      waveIndex: z.number(),
      stageIds: z.array(z.string()),
    })),
    recoveryKeyInputs: z.array(z.object({
      key: z.string(),
      value: z.union([z.string(), z.array(z.string())]),
    })),
    blockedReasons: z.array(z.string()),
  })),
  waveCheckpoints: z.array(z.object({
    waveIndex: z.number(),
    claimIntentIds: z.array(z.string()),
    candidateCount: z.number(),
    blockedCount: z.number(),
    plannedSlotDemand: z.number(),
    blockedReasons: z.array(z.string()),
  })),
  plannedSlotDemand: z.number(),
  maxPlannedWaveWidth: z.number(),
  blockedCount: z.number(),
  recoveryKeyCoverage: z.enum(["complete", "partial"]),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const schedulerLaunchRequirementSchema = z.object({
  id: z.string(),
  status: z.enum(["required", "blocked"]),
  description: z.string(),
});

export const schedulerLaunchPreflightSchema: z.ZodType<SchedulerLaunchPreflight> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  status: z.enum(["checked", "blocked", "rejected"]),
  schedulerMode: z.literal("parallel-readiness-v1"),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  workflowGraphPlanId: z.string(),
  claimSummaries: z.array(z.object({
    claimIntentId: z.string(),
    plannedWorkerKey: z.string(),
    nodeId: z.string(),
    unitId: z.string(),
    waveIndex: z.number(),
    status: z.enum(["planned", "blocked"]),
    plannedSlotDemand: z.number(),
    sourceScopes: z.array(z.string()),
    blockedReasons: z.array(z.string()),
  })),
  sourceLockSummaries: z.array(z.object({
    scope: z.string(),
    waveIndexes: z.array(z.number()),
    claimIntentIds: z.array(z.string()),
    status: z.enum(["clear", "blocked"]),
    blockedReasons: z.array(z.string()),
  })),
  plannedSlotDemand: z.number(),
  maxPlannedWaveWidth: z.number(),
  blockedCount: z.number(),
  runtimeContinuityRequirements: z.array(schedulerLaunchRequirementSchema),
  permissionProfileRequirements: z.array(schedulerLaunchRequirementSchema),
  toolPolicyGateRequirement: schedulerLaunchRequirementSchema,
  humanGateRequirement: schedulerLaunchRequirementSchema,
  blockedReasons: z.array(z.string()),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRunSchema: z.ZodType<SchedulerRun> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  changeId: z.string(),
  status: z.enum(["prepared", "blocked", "abandoned", "completed"]),
  schedulerMode: z.literal("parallel-readiness-v1"),
  schedulerContractId: z.string(),
  schedulerDispatchDryRunId: z.string(),
  schedulerWorkerPlanId: z.string(),
  schedulerClaimReconcilePlanId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  workflowGraphPlanId: z.string(),
  claimIntentCount: z.number(),
  plannedSlotDemand: z.number(),
  maxPlannedWaveWidth: z.number(),
  blockedCount: z.number(),
  humanConfirmed: z.boolean(),
  futureToolPolicyGateRequired: z.boolean(),
  futureHumanGateRequired: z.boolean(),
  sourceArtifactHashes: z.record(z.string()),
  artifactRefs: z.array(z.string()),
  artifact: z.string(),
  markdownArtifact: z.string(),
  journalArtifact: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const schedulerRunJournalEventSchema: z.ZodType<SchedulerRunJournalEvent> = z.object({
  version: z.literal("1.0"),
  id: z.string(),
  schedulerRunId: z.string(),
  changeId: z.string(),
  schedulerLaunchPreflightId: z.string(),
  type: z.enum(["scheduler-run.prepared", "scheduler-run.blocked", "scheduler-run.abandoned", "scheduler-run.completed"]),
  timestamp: z.string(),
  status: z.enum(["prepared", "blocked", "abandoned", "completed"]).optional(),
  summary: z.string().optional(),
  artifactRefs: z.array(z.string()).optional(),
  payload: z.record(z.unknown()).optional(),
});
