import { describe, expect, it } from "vitest";
import { buildSchedulerControlledLoopRuntimeBoundary } from "../../src/scheduler-runtime/controlled-loop-runtime-boundary.js";
import type { SchedulerControlledStepForbiddenAuthority } from "../../src/scheduler-runtime/types.js";

const forbiddenAuthority: SchedulerControlledStepForbiddenAuthority = {
  loopAuthorized: false,
  wholeWaveDispatchAuthorized: false,
  slotAllocatorAuthorized: false,
  fullParallelExecutorAuthorized: false,
  sourceMutationAuthorized: false,
  applyAuthorized: false,
  closeAuthorized: false,
  mergeAuthorized: false,
  remoteLandingAuthorized: false,
  harnessEvolutionAuthorized: false,
};

describe("controlled scheduler loop runtime boundary evidence", () => {
  it("composes existing controlled-loop summaries without granting execution authority", () => {
    const boundary = buildSchedulerControlledLoopRuntimeBoundary({
      changeId: "change-1",
      schedulerRunId: "scheduler-run-1",
      controlledLoopCurrentTransitionChoice: {
        version: "1.0",
        authority: "scheduler-runtime-current-transition-choice",
        status: "ready-for-dispatch",
        changeId: "change-1",
        selectedActionType: "planning.scheduler.worker.start-next",
        submittedActionType: "planning.scheduler.controlled-advance.run",
        currentGate: {
          actionType: "planning.scheduler.worker.start-next",
          scope: { changeId: "change-1", schedulerRunId: "scheduler-run-1" },
        },
        goalLoopDecisionId: "decision-pre",
        goalLoopIterationId: "iteration-pre",
        goalLoopContinuationBriefId: "brief-pre",
        goalLoopNextStepPacketId: "packet-pre",
        goalLoopControllerPolicyId: "controller-pre",
        goalLoopGateReadinessPreflightId: "preflight-pre",
        humanGateRequired: true,
        humanConfirmationStillRequired: true,
        executionStarted: false,
        concreteGateInvoked: false,
        toolPolicyAuthorizedConcreteGate: false,
        authorizationGranted: false,
        ...forbiddenAuthority,
      },
      controlledLoopTick: {
        version: "1.0",
        authority: "scheduler-runtime-controlled-loop-tick-contract-summary",
        observe: {
          status: "recorded",
          goalLoopDecisionId: "decision-pre",
          goalLoopIterationId: "iteration-pre",
          goalLoopContinuationBriefId: "brief-pre",
          goalLoopNextStepPacketId: "packet-pre",
          submittedActionType: "planning.scheduler.worker.start-next",
        },
        chooseCheck: {
          status: "recorded",
          goalLoopControllerPolicyId: "controller-pre",
          goalLoopGateReadinessPreflightId: "preflight-pre",
          targetScopeMatched: true,
          concreteGatePreflightNonExecuting: true,
        },
        dispatch: {
          status: "completed",
          executedActionType: "planning.scheduler.worker.start-next",
          executionStarted: true,
          stoppedAfterOneSchedulerTransition: true,
          approvedScopeOnly: true,
        },
        reconcile: {
          status: "recorded",
          goalLoopNextStepPacketId: "packet-post",
          executionStarted: false,
        },
        routeStop: {
          status: "next-confirmation-candidate-ready",
          stopReason: "one-confirmed-scheduler-transition-completed",
          routePosture: "awaiting-human-gate",
          nextCandidateActionType: "planning.scheduler.worker.reconcile-result",
          humanGateRequired: true,
          humanConfirmationStillRequired: true,
          needsReevaluation: false,
        },
        resultKind: "schedulerWorkerStart",
        resultId: "worker-start-1",
        resultStatus: "started",
        executionStarted: false,
        ...forbiddenAuthority,
      },
      controlledLoopContinuationReadiness: {
        version: "1.0",
        authority: "scheduler-runtime-controlled-loop-continuation-readiness",
        status: "ready-for-human-gate",
        routePosture: "awaiting-human-gate",
        executedActionType: "planning.scheduler.worker.start-next",
        nextCandidateActionType: "planning.scheduler.worker.reconcile-result",
        resultKind: "schedulerWorkerStart",
        resultId: "worker-start-1",
        resultStatus: "started",
        reason: "ready",
        boundary: "read-only",
        readinessEvidencePrepared: true,
        needsReevaluation: false,
        humanGateRequired: true,
        humanConfirmationStillRequired: true,
        evidenceRefs: ["step.md"],
        executionStarted: false,
        ...forbiddenAuthority,
      },
      controlledLoopIteration: {
        version: "1.0",
        authority: "scheduler-runtime-controlled-loop-iteration-summary",
        status: "completed",
        executedActionType: "planning.scheduler.worker.start-next",
        observeStatus: "recorded",
        chooseCheckStatus: "recorded",
        dispatchStatus: "completed",
        reconcileStatus: "recorded",
        routePosture: "awaiting-human-gate",
        routeStopReason: "one-confirmed-scheduler-transition-completed",
        continuationReadinessStatus: "ready-for-human-gate",
        nextCandidateActionType: "planning.scheduler.worker.reconcile-result",
        resultKind: "schedulerWorkerStart",
        resultId: "worker-start-1",
        resultStatus: "started",
        readinessEvidencePrepared: true,
        needsReevaluation: false,
        humanGateRequired: true,
        humanConfirmationStillRequired: true,
        stoppedAfterOneSchedulerTransition: true,
        approvedScopeOnly: true,
        boundary: "read-only",
        evidenceRefs: ["step.md"],
        executionStarted: false,
        ...forbiddenAuthority,
      },
      controlledLoopStopSummary: {
        version: "1.0",
        authority: "scheduler-runtime-controlled-loop-stop-summary",
        executedActionType: "planning.scheduler.worker.start-next",
        stopReason: "one-confirmed-scheduler-transition-completed",
        routePosture: "awaiting-human-gate",
        continuationReadinessStatus: "ready-for-human-gate",
        nextGateActionType: "planning.scheduler.worker.reconcile-result",
        resultKind: "schedulerWorkerStart",
        resultId: "worker-start-1",
        resultStatus: "started",
        humanGateRequired: true,
        readinessEvidencePrepared: true,
        needsReevaluation: false,
        humanConfirmationStillRequired: true,
        userFacingReason: "ready",
        boundary: "read-only",
        evidenceRefs: ["step.md"],
        executionStarted: false,
        ...forbiddenAuthority,
      },
      controlledLoopBoundaryResult: {
        version: "1.0",
        authority: "scheduler-runtime-controlled-loop-boundary-result",
        status: "recorded",
        selectedActionType: "planning.scheduler.worker.start-next",
        submittedActionType: "planning.scheduler.controlled-advance.run",
        dispatchedActionType: "planning.scheduler.worker.start-next",
        selectedGateScope: { changeId: "change-1", schedulerRunId: "scheduler-run-1" },
        observeStatus: "recorded",
        chooseCheckStatus: "recorded",
        dispatchStatus: "completed",
        reconcileStatus: "recorded",
        boundaryPosture: "awaiting-human-gate",
        continuationReadinessStatus: "ready-for-human-gate",
        stopReason: "one-confirmed-scheduler-transition-completed",
        nextGateActionType: "planning.scheduler.worker.reconcile-result",
        nextGateTargetScopeSource: "fresh-current-gate-required",
        resultKind: "schedulerWorkerStart",
        resultId: "worker-start-1",
        resultStatus: "started",
        readinessEvidencePrepared: true,
        needsReevaluation: false,
        humanGateRequired: true,
        humanConfirmationStillRequired: true,
        futureContinuationRequiresFreshEvidence: true,
        futureContinuationRequiresFreshCurrentGate: true,
        stoppedAfterOneSchedulerTransition: true,
        approvedScopeOnly: true,
        boundary: "prior-turn",
        evidenceRefs: ["boundary.json"],
        executionStarted: false,
        ...forbiddenAuthority,
      },
      forbiddenAuthority,
      evidenceRefs: ["step.json"],
    });

    expect(boundary).toMatchObject({
      authority: "scheduler-runtime-controlled-loop-runtime-boundary-evidence",
      status: "recorded",
      stopPosture: "awaiting-human-gate",
      nextGateTargetScopeSource: "fresh-current-gate-required",
      priorTurnEvidence: true,
      freshEvidenceRequiredBeforeContinuation: true,
      executionStarted: false,
      loopAuthorized: false,
      fullParallelExecutorAuthorized: false,
      wholeWaveDispatchAuthorized: false,
      slotAllocatorAuthorized: false,
      sourceMutationAuthorized: false,
      applyAuthorized: false,
      closeAuthorized: false,
      mergeAuthorized: false,
      remoteLandingAuthorized: false,
      harnessEvolutionAuthorized: false,
    });
    expect(boundary?.boundary).toContain("It is prior-turn evidence only");
  });

  it("does not create a runtime-boundary summary without existing current-transition and boundary evidence", () => {
    expect(buildSchedulerControlledLoopRuntimeBoundary({
      changeId: "change-1",
      controlledLoopTick: {} as never,
      controlledLoopContinuationReadiness: {} as never,
      controlledLoopIteration: {} as never,
      controlledLoopStopSummary: {} as never,
      forbiddenAuthority,
    })).toBeUndefined();
  });
});
